/**
 * AbortXfer Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { S32, U64 } from "../types"

export interface AbortXferData {
	xferId?: {
		id: number | bigint
		result: number
	}
}

export const abortXferMetadata = {
	id: 157,
	name: "AbortXfer",
	frequency: 2,
	blocks: [
		{
			name: "xferId",
			parameters: [
				["id", U64],
				["result", S32],
			],
		},
	],
} satisfies PacketMetadata

export const abortXfer = createPacketSender<AbortXferData>(abortXferMetadata)

export const createAbortXferDelegate =
	createPacketDelegate<AbortXferData>(abortXferMetadata)
