/**
 * AcceptCallingCard Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface AcceptCallingCardData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	transactionBlock?: {
		transactionId: string
	}
	folderData?: {
		folderId: string
	}[]
}

export class AcceptCallingCard extends Packet<AcceptCallingCardData> {
	public static override id = 302
	public static override frequency = 0
	public static override trusted = false
	public static override compression = false

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["agentId", Types.UUID],
					["sessionId", Types.UUID],
				]),
			},
		],
		[
			"transactionBlock",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["transactionId", Types.UUID],
				]),
			},
		],
		[
			"folderData",
			{
				parameters: new Map<string, Types.Type>([["folderId", Types.UUID]]),
			},
		],
	])
}
