/**
 * ActivateGroup Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { UUID } from "../types"

export interface ActivateGroupData {
	agentData: {
		agentId?: string
		sessionId?: string
		groupId: string
	}
}

export const activateGroupMetadata = {
	id: 368,
	name: "ActivateGroup",
	frequency: 2,
	compression: true,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
				["groupId", UUID],
			],
		},
	],
} satisfies PacketMetadata

export const activateGroup = createPacketSender<ActivateGroupData>(
	activateGroupMetadata,
)

export const createActivateGroupDelegate =
	createPacketDelegate<ActivateGroupData>(activateGroupMetadata)
