/**
 * AgentDataUpdate Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface AgentDataUpdateData {
	agentData: {
		agentId?: string | Buffer
		firstName: string | Buffer
		lastName: string | Buffer
		groupTitle: string | Buffer
		activeGroupId: string | Buffer
		groupPowers: number | bigint
		groupName: string | Buffer
	}
}

export class AgentDataUpdate extends Packet<AgentDataUpdateData> {
	public static override id = 387
	public static override frequency = 0
	public static override trusted = true
	public static override compression = true

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["agentId", Types.UUID],
					["firstName", Types.Variable1],
					["lastName", Types.Variable1],
					["groupTitle", Types.Variable1],
					["activeGroupId", Types.UUID],
					["groupPowers", Types.U64],
					["groupName", Types.Variable1],
				]),
			},
		],
	])
}
