/**
 * AgentAnimation Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface AgentAnimationData {
	agentData?: {
		agentId?: string | Buffer
		sessionId?: string | Buffer
	}
	animationList?: {
		animId: string | Buffer
		startAnim: boolean
	}[]
	physicalAvatarEventList?: {
		typeData: string | Buffer
	}[]
}

export class AgentAnimation extends Packet<AgentAnimationData> {
	public static override id = 5
	public static override frequency = 2
	public static override trusted = false
	public static override compression = false

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["agentId", Types.UUID],
					["sessionId", Types.UUID],
				]),
			},
		],
		[
			"animationList",
			{
				parameters: new Map<string, Types.Type>([
					["animId", Types.UUID],
					["startAnim", Types.Bool],
				]),
			},
		],
		[
			"physicalAvatarEventList",
			{
				parameters: new Map<string, Types.Type>([
					["typeData", Types.Variable1],
				]),
			},
		],
	])
}
