/**
 * AgentWearablesUpdate Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "~/network/types"
import { Packet } from "./packet"

export interface AgentWearablesUpdateData {
	agentData: {
		agentId?: string
		sessionId?: string
		serialNum: number
	}
	wearableData?: {
		itemId: string
		assetId: string
		wearableType: number
	}[]
}

export class AgentWearablesUpdate extends Packet<AgentWearablesUpdateData> {
	public static override id = 382
	public static override frequency = 0
	public static override trusted = true
	public static override compression = true

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["agentId", Types.UUID],
					["sessionId", Types.UUID],
					["serialNum", Types.U32],
				]),
			},
		],
		[
			"wearableData",
			{
				parameters: new Map<string, Types.Type>([
					["itemId", Types.UUID],
					["assetId", Types.UUID],
					["wearableType", Types.U8],
				]),
			},
		],
	])
}
