/**
 * AgentRequestSit Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface AgentRequestSitData {
	agentData?: {
		agentId?: string | Buffer
		sessionId?: string | Buffer
	}
	targetObject?: {
		targetId: string | Buffer
		offset: Types.Vector3
	}
}

export class AgentRequestSit extends Packet<AgentRequestSitData> {
	public static override id = 6
	public static override frequency = 2
	public static override trusted = false
	public static override compression = true

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["agentId", Types.UUID],
					["sessionId", Types.UUID],
				]),
			},
		],
		[
			"targetObject",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["targetId", Types.UUID],
					["offset", Types.Vector3],
				]),
			},
		],
	])
}
