/**
 * AgentAlertMessage Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { Bool, UUID, Variable1 } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface AgentAlertMessageData {
	agentData?: {
		agentId?: string
	}
	alertData?: {
		modal: boolean
		message: string | Buffer
	}
}

export const agentAlertMessageMetadata = {
	id: 135,
	name: "AgentAlertMessage",
	frequency: 2,
	trusted: true,
	blocks: [
		{
			name: "agentData",
			parameters: [["agentId", UUID]],
		},
		{
			name: "alertData",
			parameters: [
				["modal", Bool],
				["message", Variable1],
			],
		},
	],
} satisfies PacketMetadata

export const agentAlertMessage = createPacketSender<AgentAlertMessageData>(
	agentAlertMessageMetadata,
)

export const createAgentAlertMessageDelegate =
	createPacketDelegate<AgentAlertMessageData>(agentAlertMessageMetadata)
