/**
 * AgentDropGroup Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface AgentDropGroupData {
	agentData: {
		agentId?: string
		groupId: string
	}
}

export class AgentDropGroup extends Packet<AgentDropGroupData> {
	public static override id = 390
	public static override frequency = 0
	public static override trusted = true
	public static override compression = true

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["agentId", Types.UUID],
					["groupId", Types.UUID],
				]),
			},
		],
	])
}
