/**
 * AgentUpdate Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface AgentUpdateData {
	agentData: {
		agentId?: string
		sessionId?: string
		bodyRotation: Types.Quaternion
		headRotation: Types.Quaternion
		state: number
		cameraCenter: Types.Vector3
		cameraAtAxis: Types.Vector3
		cameraLeftAxis: Types.Vector3
		cameraUpAxis: Types.Vector3
		far: number
		controlFlags: number
		flags?: number
	}
}

export class AgentUpdate extends Packet<AgentUpdateData> {
	public static override id = 4
	public static override frequency = 2
	public static override trusted = false
	public static override compression = true

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["agentId", Types.UUID],
					["sessionId", Types.UUID],
					["bodyRotation", Types.Quaternion],
					["headRotation", Types.Quaternion],
					["state", Types.U8],
					["cameraCenter", Types.Vector3],
					["cameraAtAxis", Types.Vector3],
					["cameraLeftAxis", Types.Vector3],
					["cameraUpAxis", Types.Vector3],
					["far", Types.F32],
					["controlFlags", Types.U32],
					["flags", Types.U8],
				]),
			},
		],
	])
}
