/**
 * AgentFOV Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { F32, U32, UUID } from "../types"

export interface AgentFOVData {
	agentData?: {
		agentId?: string
		sessionId?: string
		circuitCode?: number
	}
	fovBlock?: {
		genCounter: number
		verticalAngle: number
	}
}

export const agentFovMetadata = {
	id: 82,
	name: "AgentFOV",
	frequency: 2,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
				["circuitCode", U32],
			],
		},
		{
			name: "fovBlock",
			parameters: [
				["genCounter", U32],
				["verticalAngle", F32],
			],
		},
	],
} satisfies PacketMetadata

export const agentFov = createPacketSender<AgentFOVData>(agentFovMetadata)

export const createAgentFOVDelegate =
	createPacketDelegate<AgentFOVData>(agentFovMetadata)
