/**
 * AlertMessage Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { Variable1 } from "../types"

export interface AlertMessageData {
	alertData?: {
		message: string | Buffer
	}
	alertInfo?: {
		message: string | Buffer
		extraParams: string | Buffer
	}[]
}

export const alertMessageMetadata = {
	id: 134,
	name: "AlertMessage",
	frequency: 2,
	trusted: true,
	blocks: [
		{
			name: "alertData",
			parameters: [["message", Variable1]],
		},
		{
			name: "alertInfo",
			parameters: [
				["message", Variable1],
				["extraParams", Variable1],
			],
			multiple: true,
		},
	],
} satisfies PacketMetadata

export const alertMessage =
	createPacketSender<AlertMessageData>(alertMessageMetadata)

export const createAlertMessageDelegate =
	createPacketDelegate<AlertMessageData>(alertMessageMetadata)
