/**
 * AssetUploadRequest Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { Bool, S8, UUID, Variable2 } from "../types"

export interface AssetUploadRequestData {
	assetBlock?: {
		transactionId: string
		type: number
		tempfile: boolean
		storeLocal: boolean
		assetData: string | Buffer
	}
}

export const assetUploadRequestMetadata = {
	id: 333,
	name: "AssetUploadRequest",
	frequency: 2,
	blocks: [
		{
			name: "assetBlock",
			parameters: [
				["transactionId", UUID],
				["type", S8],
				["tempfile", Bool],
				["storeLocal", Bool],
				["assetData", Variable2],
			],
		},
	],
} satisfies PacketMetadata

export const assetUploadRequest = createPacketSender<AssetUploadRequestData>(
	assetUploadRequestMetadata,
)

export const createAssetUploadRequestDelegate =
	createPacketDelegate<AssetUploadRequestData>(assetUploadRequestMetadata)
