/**
 * AssetUploadComplete Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { Bool, S8, UUID } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface AssetUploadCompleteData {
	assetBlock?: {
		uuid: string
		type: number
		success: boolean
	}
}

export const assetUploadCompleteMetadata = {
	id: 334,
	name: "AssetUploadComplete",
	frequency: 2,
	blocks: [
		{
			name: "assetBlock",
			parameters: [
				["uuid", UUID],
				["type", S8],
				["success", Bool],
			],
		},
	],
} satisfies PacketMetadata

export const assetUploadComplete = createPacketSender<AssetUploadCompleteData>(
	assetUploadCompleteMetadata,
)

export const createAssetUploadCompleteDelegate =
	createPacketDelegate<AssetUploadCompleteData>(assetUploadCompleteMetadata)
