/**
 * AtomicPassObject Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { Bool, UUID } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface AtomicPassObjectData {
	taskData?: {
		taskId: string
		attachmentNeedsSave: boolean
	}
}

export const atomicPassObjectMetadata = {
	id: 28,
	name: "AtomicPassObject",
	trusted: true,
	blocks: [
		{
			name: "taskData",
			parameters: [
				["taskId", UUID],
				["attachmentNeedsSave", Bool],
			],
		},
	],
} satisfies PacketMetadata

export const atomicPassObject = createPacketSender<AtomicPassObjectData>(
	atomicPassObjectMetadata,
)

export const createAtomicPassObjectDelegate =
	createPacketDelegate<AtomicPassObjectData>(atomicPassObjectMetadata)
