/**
 * AvatarPropertiesUpdate Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "~/network/types"
import { Packet } from "./packet"

export interface AvatarPropertiesUpdateData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	propertiesData?: {
		imageId: string
		fLImageId: string
		aboutText: string | Buffer
		fLAboutText: string | Buffer
		allowPublish: boolean
		maturePublish: boolean
		profileUrl: string | Buffer
	}
}

export class AvatarPropertiesUpdate extends Packet<AvatarPropertiesUpdateData> {
	public static override id = 174
	public static override frequency = 0
	public static override trusted = false
	public static override compression = true

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["agentId", Types.UUID],
					["sessionId", Types.UUID],
				]),
			},
		],
		[
			"propertiesData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["imageId", Types.UUID],
					["fLImageId", Types.UUID],
					["aboutText", Types.Variable2],
					["fLAboutText", Types.Variable1],
					["allowPublish", Types.Bool],
					["maturePublish", Types.Bool],
					["profileUrl", Types.Variable1],
				]),
			},
		],
	])
}
