/**
 * AvatarPropertiesUpdate Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { Bool, UUID, Variable1, Variable2 } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface AvatarPropertiesUpdateData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	propertiesData?: {
		imageId: string
		fLImageId: string
		aboutText: string | Buffer
		fLAboutText: string | Buffer
		allowPublish: boolean
		maturePublish: boolean
		profileUrl: string | Buffer
	}
}

export const avatarPropertiesUpdateMetadata = {
	id: 174,
	name: "AvatarPropertiesUpdate",
	frequency: 2,
	compression: true,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
			],
		},
		{
			name: "propertiesData",
			parameters: [
				["imageId", UUID],
				["fLImageId", UUID],
				["aboutText", Variable2],
				["fLAboutText", Variable1],
				["allowPublish", Bool],
				["maturePublish", Bool],
				["profileUrl", Variable1],
			],
		},
	],
} satisfies PacketMetadata

export const avatarPropertiesUpdate =
	createPacketSender<AvatarPropertiesUpdateData>(avatarPropertiesUpdateMetadata)

export const createAvatarPropertiesUpdateDelegate =
	createPacketDelegate<AvatarPropertiesUpdateData>(
		avatarPropertiesUpdateMetadata,
	)
