/**
 * AvatarClassifiedReply Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "~/network/types"
import { Packet } from "./packet"

export interface AvatarClassifiedReplyData {
	agentData: {
		agentId?: string
		targetId: string
	}
	data?: {
		classifiedId: string
		name: string | Buffer
	}[]
}

export class AvatarClassifiedReply extends Packet<AvatarClassifiedReplyData> {
	public static override id = 42
	public static override frequency = 0
	public static override trusted = true
	public static override compression = false

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["agentId", Types.UUID],
					["targetId", Types.UUID],
				]),
			},
		],
		[
			"data",
			{
				parameters: new Map<string, Types.Type>([
					["classifiedId", Types.UUID],
					["name", Types.Variable1],
				]),
			},
		],
	])
}
