/**
 * AvatarAnimation Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "~/network/types"
import { Packet } from "./packet"

export interface AvatarAnimationData {
	sender?: {
		id: string
	}
	animationList?: {
		animId: string
		animSequenceId: number
	}[]
	animationSourceList?: {
		objectId: string
	}[]
	physicalAvatarEventList?: {
		typeData: string | Buffer
	}[]
}

export class AvatarAnimation extends Packet<AvatarAnimationData> {
	public static override id = 20
	public static override frequency = 2
	public static override trusted = true
	public static override compression = false

	public static override format = new Map([
		[
			"sender",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([["id", Types.UUID]]),
			},
		],
		[
			"animationList",
			{
				parameters: new Map<string, Types.Type>([
					["animId", Types.UUID],
					["animSequenceId", Types.S32],
				]),
			},
		],
		[
			"animationSourceList",
			{
				parameters: new Map<string, Types.Type>([["objectId", Types.UUID]]),
			},
		],
		[
			"physicalAvatarEventList",
			{
				parameters: new Map<string, Types.Type>([
					["typeData", Types.Variable1],
				]),
			},
		],
	])
}
