/**
 * AvatarSitResponse Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "~/network/types"
import { Packet } from "./packet"

export interface AvatarSitResponseData {
	sitObject?: {
		id: string
	}
	sitTransform?: {
		autoPilot: boolean
		sitPosition: Types.Vector3
		sitRotation: Types.Quaternion
		cameraEyeOffset: Types.Vector3
		cameraAtOffset: Types.Vector3
		forceMouselook: boolean
	}
}

export class AvatarSitResponse extends Packet<AvatarSitResponseData> {
	public static override id = 21
	public static override frequency = 2
	public static override trusted = true
	public static override compression = true

	public static override format = new Map([
		[
			"sitObject",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([["id", Types.UUID]]),
			},
		],
		[
			"sitTransform",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["autoPilot", Types.Bool],
					["sitPosition", Types.Vector3],
					["sitRotation", Types.Quaternion],
					["cameraEyeOffset", Types.Vector3],
					["cameraAtOffset", Types.Vector3],
					["forceMouselook", Types.Bool],
				]),
			},
		],
	])
}
