/**
 * AvatarGroupsReply Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "~/network/types"
import { Packet } from "./packet"

export interface AvatarGroupsReplyData {
	agentData: {
		agentId?: string
		avatarId: string
	}
	groupData?: {
		groupPowers: number | bigint
		acceptNotices: boolean
		groupTitle: string | Buffer
		groupId: string
		groupName: string | Buffer
		groupInsigniaId: string
	}[]
	newGroupData?: {
		listInProfile: boolean
	}
}

export class AvatarGroupsReply extends Packet<AvatarGroupsReplyData> {
	public static override id = 173
	public static override frequency = 0
	public static override trusted = true
	public static override compression = true

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["agentId", Types.UUID],
					["avatarId", Types.UUID],
				]),
			},
		],
		[
			"groupData",
			{
				parameters: new Map<string, Types.Type>([
					["groupPowers", Types.U64],
					["acceptNotices", Types.Bool],
					["groupTitle", Types.Variable1],
					["groupId", Types.UUID],
					["groupName", Types.Variable1],
					["groupInsigniaId", Types.UUID],
				]),
			},
		],
		[
			"newGroupData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["listInProfile", Types.Bool],
				]),
			},
		],
	])
}
