/**
 * AvatarPickerReply Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface AvatarPickerReplyData {
	agentData: {
		agentId?: string | Buffer
		queryId: string | Buffer
	}
	data?: {
		avatarId: string | Buffer
		firstName: string | Buffer
		lastName: string | Buffer
	}[]
}

export class AvatarPickerReply extends Packet<AvatarPickerReplyData> {
	public static override id = 28
	public static override frequency = 0
	public static override trusted = true
	public static override compression = false

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["agentId", Types.UUID],
					["queryId", Types.UUID],
				]),
			},
		],
		[
			"data",
			{
				parameters: new Map<string, Types.Type>([
					["avatarId", Types.UUID],
					["firstName", Types.Variable1],
					["lastName", Types.Variable1],
				]),
			},
		],
	])
}
