/**
 * AvatarPickerReply Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { UUID, Variable1 } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface AvatarPickerReplyData {
	agentData: {
		agentId?: string
		queryId: string
	}
	data?: {
		avatarId: string
		firstName: string | Buffer
		lastName: string | Buffer
	}[]
}

export const avatarPickerReplyMetadata = {
	id: 28,
	name: "AvatarPickerReply",
	frequency: 2,
	trusted: true,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["queryId", UUID],
			],
		},
		{
			name: "data",
			parameters: [
				["avatarId", UUID],
				["firstName", Variable1],
				["lastName", Variable1],
			],
			multiple: true,
		},
	],
} satisfies PacketMetadata

export const avatarPickerReply = createPacketSender<AvatarPickerReplyData>(
	avatarPickerReplyMetadata,
)

export const createAvatarPickerReplyDelegate =
	createPacketDelegate<AvatarPickerReplyData>(avatarPickerReplyMetadata)
