/**
 * AvatarInterestsReply Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { U32, UUID, Variable1 } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface AvatarInterestsReplyData {
	agentData: {
		agentId?: string
		avatarId: string
	}
	propertiesData?: {
		wantToMask: number
		wantToText: string | Buffer
		skillsMask: number
		skillsText: string | Buffer
		languagesText: string | Buffer
	}
}

export const avatarInterestsReplyMetadata = {
	id: 172,
	name: "AvatarInterestsReply",
	frequency: 2,
	trusted: true,
	compression: true,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["avatarId", UUID],
			],
		},
		{
			name: "propertiesData",
			parameters: [
				["wantToMask", U32],
				["wantToText", Variable1],
				["skillsMask", U32],
				["skillsText", Variable1],
				["languagesText", Variable1],
			],
		},
	],
} satisfies PacketMetadata

export const avatarInterestsReply =
	createPacketSender<AvatarInterestsReplyData>(avatarInterestsReplyMetadata)

export const createAvatarInterestsReplyDelegate =
	createPacketDelegate<AvatarInterestsReplyData>(avatarInterestsReplyMetadata)
