/**
 * CameraConstraint Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { Vector4 } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface CameraConstraintData {
	cameraCollidePlane?: {
		plane: Vector4
	}
}

export const cameraConstraintMetadata = {
	id: 22,
	name: "CameraConstraint",
	trusted: true,
	compression: true,
	blocks: [
		{
			name: "cameraCollidePlane",
			parameters: [["plane", Vector4]],
		},
	],
} satisfies PacketMetadata

export const cameraConstraint = createPacketSender<CameraConstraintData>(
	cameraConstraintMetadata,
)

export const createCameraConstraintDelegate =
	createPacketDelegate<CameraConstraintData>(cameraConstraintMetadata)
