/**
 * ChangeUserRights Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { S32, UUID } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface ChangeUserRightsData {
	agentData?: {
		agentId?: string
	}
	rights?: {
		agentRelated: string
		relatedRights: number
	}[]
}

export const changeUserRightsMetadata = {
	id: 321,
	name: "ChangeUserRights",
	frequency: 2,
	trusted: true,
	blocks: [
		{
			name: "agentData",
			parameters: [["agentId", UUID]],
		},
		{
			name: "rights",
			parameters: [
				["agentRelated", UUID],
				["relatedRights", S32],
			],
			multiple: true,
		},
	],
} satisfies PacketMetadata

export const changeUserRights = createPacketSender<ChangeUserRightsData>(
	changeUserRightsMetadata,
)

export const createChangeUserRightsDelegate =
	createPacketDelegate<ChangeUserRightsData>(changeUserRightsMetadata)
