/**
 * ChatFromViewer Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface ChatFromViewerData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	chatData?: {
		message: string | Buffer
		type: number
		channel: number
	}
}

export class ChatFromViewer extends Packet<ChatFromViewerData> {
	public static override id = 80
	public static override frequency = 0
	public static override trusted = false
	public static override compression = true

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["agentId", Types.UUID],
					["sessionId", Types.UUID],
				]),
			},
		],
		[
			"chatData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["message", Types.Variable2],
					["type", Types.U8],
					["channel", Types.S32],
				]),
			},
		],
	])
}
