/**
 * ChatFromSimulator Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { U8, UUID, Variable1, Variable2, Vector3 } from "../types"

export interface ChatFromSimulatorData {
	chatData?: {
		fromName: string | Buffer
		sourceId: string
		ownerId: string
		sourceType: number
		chatType: number
		audible: number
		position: Vector3
		message: string | Buffer
	}
}

export const chatFromSimulatorMetadata = {
	id: 139,
	name: "ChatFromSimulator",
	frequency: 2,
	trusted: true,
	blocks: [
		{
			name: "chatData",
			parameters: [
				["fromName", Variable1],
				["sourceId", UUID],
				["ownerId", UUID],
				["sourceType", U8],
				["chatType", U8],
				["audible", U8],
				["position", Vector3],
				["message", Variable2],
			],
		},
	],
} satisfies PacketMetadata

export const chatFromSimulator = createPacketSender<ChatFromSimulatorData>(
	chatFromSimulatorMetadata,
)

export const createChatFromSimulatorDelegate =
	createPacketDelegate<ChatFromSimulatorData>(chatFromSimulatorMetadata)
