/**
 * ClassifiedInfoReply Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { S32, U8, U32, UUID, Variable1, Variable2, Vector3D } from "../types"

export interface ClassifiedInfoReplyData {
	agentData?: {
		agentId?: string
	}
	data?: {
		classifiedId: string
		creatorId: string
		creationDate: number
		expirationDate: number
		category: number
		name: string | Buffer
		desc: string | Buffer
		parcelId: string
		parentEstate: number
		snapshotId: string
		simName: string | Buffer
		posGlobal: Vector3D
		parcelName: string | Buffer
		classifiedFlags: number
		priceForListing: number
	}
}

export const classifiedInfoReplyMetadata = {
	id: 44,
	name: "ClassifiedInfoReply",
	frequency: 2,
	trusted: true,
	blocks: [
		{
			name: "agentData",
			parameters: [["agentId", UUID]],
		},
		{
			name: "data",
			parameters: [
				["classifiedId", UUID],
				["creatorId", UUID],
				["creationDate", U32],
				["expirationDate", U32],
				["category", U32],
				["name", Variable1],
				["desc", Variable2],
				["parcelId", UUID],
				["parentEstate", U32],
				["snapshotId", UUID],
				["simName", Variable1],
				["posGlobal", Vector3D],
				["parcelName", Variable1],
				["classifiedFlags", U8],
				["priceForListing", S32],
			],
		},
	],
} satisfies PacketMetadata

export const classifiedInfoReply = createPacketSender<ClassifiedInfoReplyData>(
	classifiedInfoReplyMetadata,
)

export const createClassifiedInfoReplyDelegate =
	createPacketDelegate<ClassifiedInfoReplyData>(classifiedInfoReplyMetadata)
