/**
 * ClassifiedInfoUpdate Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "~/network/types"
import { Packet } from "./packet"

export interface ClassifiedInfoUpdateData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	data?: {
		classifiedId: string
		category: number
		name: string | Buffer
		desc: string | Buffer
		parcelId: string
		parentEstate: number
		snapshotId: string
		posGlobal: Types.Vector3D
		classifiedFlags: number
		priceForListing: number
	}
}

export class ClassifiedInfoUpdate extends Packet<ClassifiedInfoUpdateData> {
	public static override id = 45
	public static override frequency = 0
	public static override trusted = false
	public static override compression = false

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["agentId", Types.UUID],
					["sessionId", Types.UUID],
				]),
			},
		],
		[
			"data",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["classifiedId", Types.UUID],
					["category", Types.U32],
					["name", Types.Variable1],
					["desc", Types.Variable2],
					["parcelId", Types.UUID],
					["parentEstate", Types.U32],
					["snapshotId", Types.UUID],
					["posGlobal", Types.Vector3D],
					["classifiedFlags", Types.U8],
					["priceForListing", Types.S32],
				]),
			},
		],
	])
}
