/**
 * ClassifiedInfoReply Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface ClassifiedInfoReplyData {
	agentData?: {
		agentId?: string | Buffer
	}
	data?: {
		classifiedId: string | Buffer
		creatorId: string | Buffer
		creationDate: number
		expirationDate: number
		category: number
		name: string | Buffer
		desc: string | Buffer
		parcelId: string | Buffer
		parentEstate: number
		snapshotId: string | Buffer
		simName: string | Buffer
		posGlobal: Types.Vector3D
		parcelName: string | Buffer
		classifiedFlags: number
		priceForListing: number
	}
}

export class ClassifiedInfoReply extends Packet<ClassifiedInfoReplyData> {
	public static override id = 44
	public static override frequency = 0
	public static override trusted = true
	public static override compression = false

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([["agentId", Types.UUID]]),
			},
		],
		[
			"data",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["classifiedId", Types.UUID],
					["creatorId", Types.UUID],
					["creationDate", Types.U32],
					["expirationDate", Types.U32],
					["category", Types.U32],
					["name", Types.Variable1],
					["desc", Types.Variable2],
					["parcelId", Types.UUID],
					["parentEstate", Types.U32],
					["snapshotId", Types.UUID],
					["simName", Types.Variable1],
					["posGlobal", Types.Vector3D],
					["parcelName", Types.Variable1],
					["classifiedFlags", Types.U8],
					["priceForListing", Types.S32],
				]),
			},
		],
	])
}
