/**
 * ClearFollowCamProperties Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { UUID } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface ClearFollowCamPropertiesData {
	objectData?: {
		objectId: string
	}
}

export const clearFollowCamPropertiesMetadata = {
	id: 160,
	name: "ClearFollowCamProperties",
	frequency: 2,
	trusted: true,
	blocks: [
		{
			name: "objectData",
			parameters: [["objectId", UUID]],
		},
	],
} satisfies PacketMetadata

export const clearFollowCamProperties =
	createPacketSender<ClearFollowCamPropertiesData>(
		clearFollowCamPropertiesMetadata,
	)

export const createClearFollowCamPropertiesDelegate =
	createPacketDelegate<ClearFollowCamPropertiesData>(
		clearFollowCamPropertiesMetadata,
	)
