/**
 * CloseCircuit Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"

export type CloseCircuitData = Record<string, never>

export const closeCircuitMetadata = {
	id: 4294967293,
	name: "CloseCircuit",
	frequency: 3,
} satisfies PacketMetadata

export const closeCircuit =
	createPacketSender<CloseCircuitData>(closeCircuitMetadata)

export const createCloseCircuitDelegate =
	createPacketDelegate<CloseCircuitData>(closeCircuitMetadata)
