/**
 * CompletePingCheck Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { U8 } from "../types"

export interface CompletePingCheckData {
	pingId?: {
		pingId: number
	}
}

export const completePingCheckMetadata = {
	id: 2,
	name: "CompletePingCheck",
	blocks: [
		{
			name: "pingId",
			parameters: [["pingId", U8]],
		},
	],
} satisfies PacketMetadata

export const completePingCheck = createPacketSender<CompletePingCheckData>(
	completePingCheckMetadata,
)

export const createCompletePingCheckDelegate =
	createPacketDelegate<CompletePingCheckData>(completePingCheckMetadata)
