/**
 * ConfirmEnableSimulator Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface ConfirmEnableSimulatorData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
}

export class ConfirmEnableSimulator extends Packet<ConfirmEnableSimulatorData> {
	public static override id = 8
	public static override frequency = 1
	public static override trusted = true
	public static override compression = false

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["agentId", Types.UUID],
					["sessionId", Types.UUID],
				]),
			},
		],
	])
}
