/**
 * CopyInventoryItem Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface CopyInventoryItemData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	inventoryData?: {
		callbackId: number
		oldAgentId: string
		oldItemId: string
		newFolderId: string
		newName: string | Buffer
	}[]
}

export class CopyInventoryItem extends Packet<CopyInventoryItemData> {
	public static override id = 269
	public static override frequency = 0
	public static override trusted = false
	public static override compression = true

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["agentId", Types.UUID],
					["sessionId", Types.UUID],
				]),
			},
		],
		[
			"inventoryData",
			{
				parameters: new Map<string, Types.Type>([
					["callbackId", Types.U32],
					["oldAgentId", Types.UUID],
					["oldItemId", Types.UUID],
					["newFolderId", Types.UUID],
					["newName", Types.Variable1],
				]),
			},
		],
	])
}
