/**
 * CopyInventoryItem Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { U32, UUID, Variable1 } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface CopyInventoryItemData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	inventoryData?: {
		callbackId: number
		oldAgentId: string
		oldItemId: string
		newFolderId: string
		newName: string | Buffer
	}[]
}

export const copyInventoryItemMetadata = {
	id: 269,
	name: "CopyInventoryItem",
	frequency: 2,
	compression: true,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
			],
		},
		{
			name: "inventoryData",
			parameters: [
				["callbackId", U32],
				["oldAgentId", UUID],
				["oldItemId", UUID],
				["newFolderId", UUID],
				["newName", Variable1],
			],
			multiple: true,
		},
	],
} satisfies PacketMetadata

export const copyInventoryItem = createPacketSender<CopyInventoryItemData>(
	copyInventoryItemMetadata,
)

export const createCopyInventoryItemDelegate =
	createPacketDelegate<CopyInventoryItemData>(copyInventoryItemMetadata)
