/**
 * CopyInventoryFromNotecard Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { UUID } from "../types"

export interface CopyInventoryFromNotecardData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	notecardData?: {
		notecardItemId: string
		objectId: string
	}
	inventoryData?: {
		itemId: string
		folderId: string
	}[]
}

export const copyInventoryFromNotecardMetadata = {
	id: 265,
	name: "CopyInventoryFromNotecard",
	frequency: 2,
	compression: true,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
			],
		},
		{
			name: "notecardData",
			parameters: [
				["notecardItemId", UUID],
				["objectId", UUID],
			],
		},
		{
			name: "inventoryData",
			parameters: [
				["itemId", UUID],
				["folderId", UUID],
			],
			multiple: true,
		},
	],
} satisfies PacketMetadata

export const copyInventoryFromNotecard =
	createPacketSender<CopyInventoryFromNotecardData>(
		copyInventoryFromNotecardMetadata,
	)

export const createCopyInventoryFromNotecardDelegate =
	createPacketDelegate<CopyInventoryFromNotecardData>(
		copyInventoryFromNotecardMetadata,
	)
