/**
 * CreateTrustedCircuit Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { Fixed32, UUID } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface CreateTrustedCircuitData {
	dataBlock?: {
		endPointId: string
		digest: string | Buffer
	}
}

export const createTrustedCircuitMetadata = {
	id: 392,
	name: "CreateTrustedCircuit",
	frequency: 2,
	blocks: [
		{
			name: "dataBlock",
			parameters: [
				["endPointId", UUID],
				["digest", Fixed32],
			],
		},
	],
} satisfies PacketMetadata

export const createTrustedCircuit =
	createPacketSender<CreateTrustedCircuitData>(createTrustedCircuitMetadata)

export const createCreateTrustedCircuitDelegate =
	createPacketDelegate<CreateTrustedCircuitData>(createTrustedCircuitMetadata)
