/**
 * CreateGroupReply Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { Bool, UUID, Variable1 } from "../types"

export interface CreateGroupReplyData {
	agentData?: {
		agentId?: string
	}
	replyData?: {
		groupId: string
		success: boolean
		message: string | Buffer
	}
}

export const createGroupReplyMetadata = {
	id: 340,
	name: "CreateGroupReply",
	frequency: 2,
	trusted: true,
	blocks: [
		{
			name: "agentData",
			parameters: [["agentId", UUID]],
		},
		{
			name: "replyData",
			parameters: [
				["groupId", UUID],
				["success", Bool],
				["message", Variable1],
			],
		},
	],
} satisfies PacketMetadata

export const createGroupReply = createPacketSender<CreateGroupReplyData>(
	createGroupReplyMetadata,
)

export const createCreateGroupReplyDelegate =
	createPacketDelegate<CreateGroupReplyData>(createGroupReplyMetadata)
