/**
 * CreateNewOutfitAttachments Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { UUID } from "../types"

export interface CreateNewOutfitAttachmentsData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	headerData?: {
		newFolderId: string
	}
	objectData?: {
		oldItemId: string
		oldFolderId: string
	}[]
}

export const createNewOutfitAttachmentsMetadata = {
	id: 398,
	name: "CreateNewOutfitAttachments",
	frequency: 2,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
			],
		},
		{
			name: "headerData",
			parameters: [["newFolderId", UUID]],
		},
		{
			name: "objectData",
			parameters: [
				["oldItemId", UUID],
				["oldFolderId", UUID],
			],
			multiple: true,
		},
	],
} satisfies PacketMetadata

export const createNewOutfitAttachments =
	createPacketSender<CreateNewOutfitAttachmentsData>(
		createNewOutfitAttachmentsMetadata,
	)

export const createCreateNewOutfitAttachmentsDelegate =
	createPacketDelegate<CreateNewOutfitAttachmentsData>(
		createNewOutfitAttachmentsMetadata,
	)
