/**
 * CreateGroupReply Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface CreateGroupReplyData {
	agentData?: {
		agentId?: string
	}
	replyData?: {
		groupId: string
		success: boolean
		message: string | Buffer
	}
}

export class CreateGroupReply extends Packet<CreateGroupReplyData> {
	public static override id = 340
	public static override frequency = 0
	public static override trusted = true
	public static override compression = false

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([["agentId", Types.UUID]]),
			},
		],
		[
			"replyData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["groupId", Types.UUID],
					["success", Types.Bool],
					["message", Types.Variable1],
				]),
			},
		],
	])
}
