/**
 * CrossedRegion Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "~/network/types"
import { Packet } from "./packet"

export interface CrossedRegionData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	regionData?: {
		simIp: Types.IP
		simPort: Types.Port
		regionHandle: number | bigint
		seedCapability: string | Buffer
	}
	info?: {
		position: Types.Vector3
		lookAt: Types.Vector3
	}
}

export class CrossedRegion extends Packet<CrossedRegionData> {
	public static override id = 7
	public static override frequency = 1
	public static override trusted = true
	public static override compression = false

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["agentId", Types.UUID],
					["sessionId", Types.UUID],
				]),
			},
		],
		[
			"regionData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["simIp", Types.IP],
					["simPort", Types.Port],
					["regionHandle", Types.U64],
					["seedCapability", Types.Variable2],
				]),
			},
		],
		[
			"info",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["position", Types.Vector3],
					["lookAt", Types.Vector3],
				]),
			},
		],
	])
}
