/**
 * DataHomeLocationReply Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "~/network/types"
import { Packet } from "./packet"

export interface DataHomeLocationReplyData {
	info?: {
		agentId: string
		regionHandle: number | bigint
		position: Types.Vector3
		lookAt: Types.Vector3
	}
}

export class DataHomeLocationReply extends Packet<DataHomeLocationReplyData> {
	public static override id = 68
	public static override frequency = 0
	public static override trusted = true
	public static override compression = false

	public static override format = new Map([
		[
			"info",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["agentId", Types.UUID],
					["regionHandle", Types.U64],
					["position", Types.Vector3],
					["lookAt", Types.Vector3],
				]),
			},
		],
	])
}
