/**
 * DataHomeLocationRequest Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface DataHomeLocationRequestData {
	info?: {
		agentId: string | Buffer
		kickedFromEstateId: number
	}
	agentInfo?: {
		agentEffectiveMaturity: number
	}
}

export class DataHomeLocationRequest extends Packet<DataHomeLocationRequestData> {
	public static override id = 67
	public static override frequency = 0
	public static override trusted = true
	public static override compression = true

	public static override format = new Map([
		[
			"info",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["agentId", Types.UUID],
					["kickedFromEstateId", Types.U32],
				]),
			},
		],
		[
			"agentInfo",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["agentEffectiveMaturity", Types.U32],
				]),
			},
		],
	])
}
