/**
 * DataHomeLocationRequest Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { U32, UUID } from "../types"

export interface DataHomeLocationRequestData {
	info?: {
		agentId: string
		kickedFromEstateId: number
	}
	agentInfo?: {
		agentEffectiveMaturity: number
	}
}

export const dataHomeLocationRequestMetadata = {
	id: 67,
	name: "DataHomeLocationRequest",
	frequency: 2,
	trusted: true,
	compression: true,
	blocks: [
		{
			name: "info",
			parameters: [
				["agentId", UUID],
				["kickedFromEstateId", U32],
			],
		},
		{
			name: "agentInfo",
			parameters: [["agentEffectiveMaturity", U32]],
		},
	],
} satisfies PacketMetadata

export const dataHomeLocationRequest =
	createPacketSender<DataHomeLocationRequestData>(
		dataHomeLocationRequestMetadata,
	)

export const createDataHomeLocationRequestDelegate =
	createPacketDelegate<DataHomeLocationRequestData>(
		dataHomeLocationRequestMetadata,
	)
