/**
 * DeRezObject Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "~/network/types"
import { Packet } from "./packet"

export interface DeRezObjectData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	agentBlock?: {
		groupId: string
		destination: number
		destinationId: string
		transactionId: string
		packetCount: number
		packetNumber: number
	}
	objectData?: {
		objectLocalId: number
	}[]
}

export class DeRezObject extends Packet<DeRezObjectData> {
	public static override id = 291
	public static override frequency = 0
	public static override trusted = false
	public static override compression = true

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["agentId", Types.UUID],
					["sessionId", Types.UUID],
				]),
			},
		],
		[
			"agentBlock",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["groupId", Types.UUID],
					["destination", Types.U8],
					["destinationId", Types.UUID],
					["transactionId", Types.UUID],
					["packetCount", Types.U8],
					["packetNumber", Types.U8],
				]),
			},
		],
		[
			"objectData",
			{
				parameters: new Map<string, Types.Type>([["objectLocalId", Types.U32]]),
			},
		],
	])
}
