/**
 * DeRezAck Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { Bool, UUID } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface DeRezAckData {
	transactionData?: {
		transactionId: string
		success: boolean
	}
}

export const deRezAckMetadata = {
	id: 292,
	name: "DeRezAck",
	frequency: 2,
	trusted: true,
	blocks: [
		{
			name: "transactionData",
			parameters: [
				["transactionId", UUID],
				["success", Bool],
			],
		},
	],
} satisfies PacketMetadata

export const deRezAck = createPacketSender<DeRezAckData>(deRezAckMetadata)

export const createDeRezAckDelegate =
	createPacketDelegate<DeRezAckData>(deRezAckMetadata)
