/**
 * DeactivateGestures Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface DeactivateGesturesData {
	agentData?: {
		agentId?: string | Buffer
		sessionId?: string | Buffer
		flags?: number
	}
	data?: {
		itemId: string | Buffer
		gestureFlags: number
	}[]
}

export class DeactivateGestures extends Packet<DeactivateGesturesData> {
	public static override id = 317
	public static override frequency = 0
	public static override trusted = false
	public static override compression = false

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["agentId", Types.UUID],
					["sessionId", Types.UUID],
					["flags", Types.U32],
				]),
			},
		],
		[
			"data",
			{
				parameters: new Map<string, Types.Type>([
					["itemId", Types.UUID],
					["gestureFlags", Types.U32],
				]),
			},
		],
	])
}
