/**
 * DeclineCallingCard Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { UUID } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface DeclineCallingCardData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	transactionBlock?: {
		transactionId: string
	}
}

export const declineCallingCardMetadata = {
	id: 303,
	name: "DeclineCallingCard",
	frequency: 2,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
			],
		},
		{
			name: "transactionBlock",
			parameters: [["transactionId", UUID]],
		},
	],
} satisfies PacketMetadata

export const declineCallingCard = createPacketSender<DeclineCallingCardData>(
	declineCallingCardMetadata,
)

export const createDeclineCallingCardDelegate =
	createPacketDelegate<DeclineCallingCardData>(declineCallingCardMetadata)
