/**
 * DenyTrustedCircuit Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface DenyTrustedCircuitData {
	dataBlock?: {
		endPointId: string | Buffer
	}
}

export class DenyTrustedCircuit extends Packet<DenyTrustedCircuitData> {
	public static override id = 393
	public static override frequency = 0
	public static override trusted = false
	public static override compression = false

	public static override format = new Map([
		[
			"dataBlock",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([["endPointId", Types.UUID]]),
			},
		],
	])
}
