/**
 * DerezContainer Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface DerezContainerData {
	data?: {
		objectId: string | Buffer
		delete: boolean
	}
}

export class DerezContainer extends Packet<DerezContainerData> {
	public static override id = 104
	public static override frequency = 0
	public static override trusted = true
	public static override compression = true

	public static override format = new Map([
		[
			"data",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["objectId", Types.UUID],
					["delete", Types.Bool],
				]),
			},
		],
	])
}
