/**
 * DetachAttachmentIntoInv Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { UUID } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface DetachAttachmentIntoInvData {
	objectData?: {
		agentId: string
		itemId: string
	}
}

export const detachAttachmentIntoInvMetadata = {
	id: 397,
	name: "DetachAttachmentIntoInv",
	frequency: 2,
	blocks: [
		{
			name: "objectData",
			parameters: [
				["agentId", UUID],
				["itemId", UUID],
			],
		},
	],
} satisfies PacketMetadata

export const detachAttachmentIntoInv =
	createPacketSender<DetachAttachmentIntoInvData>(
		detachAttachmentIntoInvMetadata,
	)

export const createDetachAttachmentIntoInvDelegate =
	createPacketDelegate<DetachAttachmentIntoInvData>(
		detachAttachmentIntoInvMetadata,
	)
