/**
 * DirClassifiedReply Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { S32, U8, U32, UUID, Variable1 } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface DirClassifiedReplyData {
	agentData?: {
		agentId?: string
	}
	queryData?: {
		queryId: string
	}
	queryReplies?: {
		classifiedId: string
		name: string | Buffer
		classifiedFlags: number
		creationDate: number
		expirationDate: number
		priceForListing: number
	}[]
	statusData?: {
		status: number
	}[]
}

export const dirClassifiedReplyMetadata = {
	id: 41,
	name: "DirClassifiedReply",
	frequency: 2,
	trusted: true,
	compression: true,
	blocks: [
		{
			name: "agentData",
			parameters: [["agentId", UUID]],
		},
		{
			name: "queryData",
			parameters: [["queryId", UUID]],
		},
		{
			name: "queryReplies",
			parameters: [
				["classifiedId", UUID],
				["name", Variable1],
				["classifiedFlags", U8],
				["creationDate", U32],
				["expirationDate", U32],
				["priceForListing", S32],
			],
			multiple: true,
		},
		{
			name: "statusData",
			parameters: [["status", U32]],
			multiple: true,
		},
	],
} satisfies PacketMetadata

export const dirClassifiedReply = createPacketSender<DirClassifiedReplyData>(
	dirClassifiedReplyMetadata,
)

export const createDirClassifiedReplyDelegate =
	createPacketDelegate<DirClassifiedReplyData>(dirClassifiedReplyMetadata)
