/**
 * DirEventsReply Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface DirEventsReplyData {
	agentData?: {
		agentId?: string | Buffer
	}
	queryData?: {
		queryId: string | Buffer
	}
	queryReplies?: {
		ownerId: string | Buffer
		name: string | Buffer
		eventId: number
		date: string | Buffer
		unixTime: number
		eventFlags: number
	}[]
	statusData?: {
		status: number
	}[]
}

export class DirEventsReply extends Packet<DirEventsReplyData> {
	public static override id = 37
	public static override frequency = 0
	public static override trusted = true
	public static override compression = true

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([["agentId", Types.UUID]]),
			},
		],
		[
			"queryData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([["queryId", Types.UUID]]),
			},
		],
		[
			"queryReplies",
			{
				parameters: new Map<string, Types.Type>([
					["ownerId", Types.UUID],
					["name", Types.Variable1],
					["eventId", Types.U32],
					["date", Types.Variable1],
					["unixTime", Types.U32],
					["eventFlags", Types.U32],
				]),
			},
		],
		[
			"statusData",
			{
				parameters: new Map<string, Types.Type>([["status", Types.U32]]),
			},
		],
	])
}
