/**
 * DirPlacesReply Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { Bool, F32, U32, UUID, Variable1 } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface DirPlacesReplyData {
	agentData?: {
		agentId?: string
	}
	queryData?: {
		queryId: string
	}[]
	queryReplies?: {
		parcelId: string
		name: string | Buffer
		forSale: boolean
		auction: boolean
		dwell: number
	}[]
	statusData?: {
		status: number
	}[]
}

export const dirPlacesReplyMetadata = {
	id: 35,
	name: "DirPlacesReply",
	frequency: 2,
	trusted: true,
	compression: true,
	blocks: [
		{
			name: "agentData",
			parameters: [["agentId", UUID]],
		},
		{
			name: "queryData",
			parameters: [["queryId", UUID]],
			multiple: true,
		},
		{
			name: "queryReplies",
			parameters: [
				["parcelId", UUID],
				["name", Variable1],
				["forSale", Bool],
				["auction", Bool],
				["dwell", F32],
			],
			multiple: true,
		},
		{
			name: "statusData",
			parameters: [["status", U32]],
			multiple: true,
		},
	],
} satisfies PacketMetadata

export const dirPlacesReply = createPacketSender<DirPlacesReplyData>(
	dirPlacesReplyMetadata,
)

export const createDirPlacesReplyDelegate =
	createPacketDelegate<DirPlacesReplyData>(dirPlacesReplyMetadata)
