/**
 * DirGroupsReply Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { F32, S32, UUID, Variable1 } from "../types"

export interface DirGroupsReplyData {
	agentData?: {
		agentId?: string
	}
	queryData?: {
		queryId: string
	}
	queryReplies?: {
		groupId: string
		groupName: string | Buffer
		members: number
		searchOrder: number
	}[]
}

export const dirGroupsReplyMetadata = {
	id: 38,
	name: "DirGroupsReply",
	frequency: 2,
	trusted: true,
	compression: true,
	blocks: [
		{
			name: "agentData",
			parameters: [["agentId", UUID]],
		},
		{
			name: "queryData",
			parameters: [["queryId", UUID]],
		},
		{
			name: "queryReplies",
			parameters: [
				["groupId", UUID],
				["groupName", Variable1],
				["members", S32],
				["searchOrder", F32],
			],
			multiple: true,
		},
	],
} satisfies PacketMetadata

export const dirGroupsReply = createPacketSender<DirGroupsReplyData>(
	dirGroupsReplyMetadata,
)

export const createDirGroupsReplyDelegate =
	createPacketDelegate<DirGroupsReplyData>(dirGroupsReplyMetadata)
