/**
 * DirLandQuery Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { S32, U32, UUID } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface DirLandQueryData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	queryData?: {
		queryId: string
		queryFlags: number
		searchType: number
		price: number
		area: number
		queryStart: number
	}
}

export const dirLandQueryMetadata = {
	id: 48,
	name: "DirLandQuery",
	frequency: 2,
	compression: true,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
			],
		},
		{
			name: "queryData",
			parameters: [
				["queryId", UUID],
				["queryFlags", U32],
				["searchType", U32],
				["price", S32],
				["area", S32],
				["queryStart", S32],
			],
		},
	],
} satisfies PacketMetadata

export const dirLandQuery =
	createPacketSender<DirLandQueryData>(dirLandQueryMetadata)

export const createDirLandQueryDelegate =
	createPacketDelegate<DirLandQueryData>(dirLandQueryMetadata)
