/**
 * DirPopularQuery Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { U32, UUID } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface DirPopularQueryData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	queryData?: {
		queryId: string
		queryFlags: number
	}
}

export const dirPopularQueryMetadata = {
	id: 51,
	name: "DirPopularQuery",
	frequency: 2,
	compression: true,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
			],
		},
		{
			name: "queryData",
			parameters: [
				["queryId", UUID],
				["queryFlags", U32],
			],
		},
	],
} satisfies PacketMetadata

export const dirPopularQuery = createPacketSender<DirPopularQueryData>(
	dirPopularQueryMetadata,
)

export const createDirPopularQueryDelegate =
	createPacketDelegate<DirPopularQueryData>(dirPopularQueryMetadata)
