/**
 * DirClassifiedQueryBackend Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { Bool, S32, U32, UUID, Variable1 } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface DirClassifiedQueryBackendData {
	agentData?: {
		agentId?: string
	}
	queryData?: {
		queryId: string
		queryText: string | Buffer
		queryFlags: number
		category: number
		estateId: number
		godlike: boolean
		queryStart: number
	}
}

export const dirClassifiedQueryBackendMetadata = {
	id: 40,
	name: "DirClassifiedQueryBackend",
	frequency: 2,
	trusted: true,
	compression: true,
	blocks: [
		{
			name: "agentData",
			parameters: [["agentId", UUID]],
		},
		{
			name: "queryData",
			parameters: [
				["queryId", UUID],
				["queryText", Variable1],
				["queryFlags", U32],
				["category", U32],
				["estateId", U32],
				["godlike", Bool],
				["queryStart", S32],
			],
		},
	],
} satisfies PacketMetadata

export const dirClassifiedQueryBackend =
	createPacketSender<DirClassifiedQueryBackendData>(
		dirClassifiedQueryBackendMetadata,
	)

export const createDirClassifiedQueryBackendDelegate =
	createPacketDelegate<DirClassifiedQueryBackendData>(
		dirClassifiedQueryBackendMetadata,
	)
