/**
 * DirPopularQueryBackend Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface DirPopularQueryBackendData {
	agentData?: {
		agentId?: string
	}
	queryData?: {
		queryId: string
		queryFlags: number
		estateId: number
		godlike: boolean
	}
}

export class DirPopularQueryBackend extends Packet<DirPopularQueryBackendData> {
	public static override id = 52
	public static override frequency = 0
	public static override trusted = true
	public static override compression = true

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([["agentId", Types.UUID]]),
			},
		],
		[
			"queryData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["queryId", Types.UUID],
					["queryFlags", Types.U32],
					["estateId", Types.U32],
					["godlike", Types.Bool],
				]),
			},
		],
	])
}
