/**
 * DirLandQuery Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface DirLandQueryData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	queryData?: {
		queryId: string
		queryFlags: number
		searchType: number
		price: number
		area: number
		queryStart: number
	}
}

export class DirLandQuery extends Packet<DirLandQueryData> {
	public static override id = 48
	public static override frequency = 0
	public static override trusted = false
	public static override compression = true

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["agentId", Types.UUID],
					["sessionId", Types.UUID],
				]),
			},
		],
		[
			"queryData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["queryId", Types.UUID],
					["queryFlags", Types.U32],
					["searchType", Types.U32],
					["price", Types.S32],
					["area", Types.S32],
					["queryStart", Types.S32],
				]),
			},
		],
	])
}
