/**
 * EconomyDataRequest Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export type EconomyDataRequestData = Record<string, never>

export const economyDataRequestMetadata = {
	id: 24,
	name: "EconomyDataRequest",
	frequency: 2,
} satisfies PacketMetadata

export const economyDataRequest = createPacketSender<EconomyDataRequestData>(
	economyDataRequestMetadata,
)

export const createEconomyDataRequestDelegate =
	createPacketDelegate<EconomyDataRequestData>(economyDataRequestMetadata)
