/**
 * EdgeDataPacket Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { U8, Variable2 } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface EdgeDataPacketData {
	edgeData?: {
		layerType: number
		direction: number
		layerData: string | Buffer
	}
}

export const edgeDataPacketMetadata = {
	id: 24,
	name: "EdgeDataPacket",
	trusted: true,
	compression: true,
	blocks: [
		{
			name: "edgeData",
			parameters: [
				["layerType", U8],
				["direction", U8],
				["layerData", Variable2],
			],
		},
	],
} satisfies PacketMetadata

export const edgeDataPacket = createPacketSender<EdgeDataPacketData>(
	edgeDataPacketMetadata,
)

export const createEdgeDataPacketDelegate =
	createPacketDelegate<EdgeDataPacketData>(edgeDataPacketMetadata)
