/**
 * EdgeDataPacket Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "~/network/types"
import { Packet } from "./packet"

export interface EdgeDataPacketData {
	edgeData?: {
		layerType: number
		direction: number
		layerData: string | Buffer
	}
}

export class EdgeDataPacket extends Packet<EdgeDataPacketData> {
	public static override id = 24
	public static override frequency = 2
	public static override trusted = true
	public static override compression = true

	public static override format = new Map([
		[
			"edgeData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["layerType", Types.U8],
					["direction", Types.U8],
					["layerData", Types.Variable2],
				]),
			},
		],
	])
}
