/**
 * EjectGroupMemberRequest Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { UUID } from "../types"

export interface EjectGroupMemberRequestData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	groupData?: {
		groupId: string
	}
	ejectData?: {
		ejecteeId: string
	}[]
}

export const ejectGroupMemberRequestMetadata = {
	id: 345,
	name: "EjectGroupMemberRequest",
	frequency: 2,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
			],
		},
		{
			name: "groupData",
			parameters: [["groupId", UUID]],
		},
		{
			name: "ejectData",
			parameters: [["ejecteeId", UUID]],
			multiple: true,
		},
	],
} satisfies PacketMetadata

export const ejectGroupMemberRequest =
	createPacketSender<EjectGroupMemberRequestData>(
		ejectGroupMemberRequestMetadata,
	)

export const createEjectGroupMemberRequestDelegate =
	createPacketDelegate<EjectGroupMemberRequestData>(
		ejectGroupMemberRequestMetadata,
	)
