/**
 * EjectUser Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { U32, UUID } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface EjectUserData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	data?: {
		targetId: string
		flags: number
	}
}

export const ejectUserMetadata = {
	id: 167,
	name: "EjectUser",
	frequency: 2,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
			],
		},
		{
			name: "data",
			parameters: [
				["targetId", UUID],
				["flags", U32],
			],
		},
	],
} satisfies PacketMetadata

export const ejectUser = createPacketSender<EjectUserData>(ejectUserMetadata)

export const createEjectUserDelegate =
	createPacketDelegate<EjectUserData>(ejectUserMetadata)
