/**
 * EnableSimulator Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { IP, Port, U64 } from "../types"

export interface EnableSimulatorData {
	simulatorInfo?: {
		handle: number | bigint
		ip: IP
		port: Port
	}
}

export const enableSimulatorMetadata = {
	id: 151,
	name: "EnableSimulator",
	frequency: 2,
	trusted: true,
	blocks: [
		{
			name: "simulatorInfo",
			parameters: [
				["handle", U64],
				["ip", IP],
				["port", Port],
			],
		},
	],
} satisfies PacketMetadata

export const enableSimulator = createPacketSender<EnableSimulatorData>(
	enableSimulatorMetadata,
)

export const createEnableSimulatorDelegate =
	createPacketDelegate<EnableSimulatorData>(enableSimulatorMetadata)
