/**
 * Error Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { S32, UUID, Variable1, Variable2 } from "../types"

export interface ErrorData {
	agentData?: {
		agentId?: string
	}
	data?: {
		code: number
		token: string | Buffer
		id: string
		system: string | Buffer
		message: string | Buffer
		data: string | Buffer
	}
}

export const errorMetadata = {
	id: 423,
	name: "Error",
	frequency: 2,
	compression: true,
	blocks: [
		{
			name: "agentData",
			parameters: [["agentId", UUID]],
		},
		{
			name: "data",
			parameters: [
				["code", S32],
				["token", Variable1],
				["id", UUID],
				["system", Variable1],
				["message", Variable2],
				["data", Variable2],
			],
		},
	],
} satisfies PacketMetadata

export const error = createPacketSender<ErrorData>(errorMetadata)

export const createErrorDelegate =
	createPacketDelegate<ErrorData>(errorMetadata)
