/**
 * EstateCovenantReply Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface EstateCovenantReplyData {
	data?: {
		covenantId: string
		covenantTimestamp: number
		estateName: string | Buffer
		estateOwnerId: string
	}
}

export class EstateCovenantReply extends Packet<EstateCovenantReplyData> {
	public static override id = 204
	public static override frequency = 0
	public static override trusted = true
	public static override compression = false

	public static override format = new Map([
		[
			"data",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["covenantId", Types.UUID],
					["covenantTimestamp", Types.U32],
					["estateName", Types.Variable1],
					["estateOwnerId", Types.UUID],
				]),
			},
		],
	])
}
