/**
 * EstateCovenantRequest Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { UUID } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface EstateCovenantRequestData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
}

export const estateCovenantRequestMetadata = {
	id: 203,
	name: "EstateCovenantRequest",
	frequency: 2,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
			],
		},
	],
} satisfies PacketMetadata

export const estateCovenantRequest =
	createPacketSender<EstateCovenantRequestData>(estateCovenantRequestMetadata)

export const createEstateCovenantRequestDelegate =
	createPacketDelegate<EstateCovenantRequestData>(estateCovenantRequestMetadata)
