/**
 * EventGodDelete Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface EventGodDeleteData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	eventData?: {
		eventId: number
	}
	queryData?: {
		queryId: string
		queryText: string | Buffer
		queryFlags: number
		queryStart: number
	}
}

export class EventGodDelete extends Packet<EventGodDeleteData> {
	public static override id = 183
	public static override frequency = 0
	public static override trusted = false
	public static override compression = false

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["agentId", Types.UUID],
					["sessionId", Types.UUID],
				]),
			},
		],
		[
			"eventData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([["eventId", Types.U32]]),
			},
		],
		[
			"queryData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["queryId", Types.UUID],
					["queryText", Types.Variable1],
					["queryFlags", Types.U32],
					["queryStart", Types.S32],
				]),
			},
		],
	])
}
