/**
 * FeatureDisabled Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { UUID, Variable1 } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface FeatureDisabledData {
	failureInfo?: {
		errorMessage: string | Buffer
		agentId: string
		transactionId: string
	}
}

export const featureDisabledMetadata = {
	id: 19,
	name: "FeatureDisabled",
	frequency: 2,
	trusted: true,
	blocks: [
		{
			name: "failureInfo",
			parameters: [
				["errorMessage", Variable1],
				["agentId", UUID],
				["transactionId", UUID],
			],
		},
	],
} satisfies PacketMetadata

export const featureDisabled = createPacketSender<FeatureDisabledData>(
	featureDisabledMetadata,
)

export const createFeatureDisabledDelegate =
	createPacketDelegate<FeatureDisabledData>(featureDisabledMetadata)
