/**
 * FetchInventoryReply Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { Bool, S8, S32, U8, U32, UUID, Variable1 } from "../types"

export interface FetchInventoryReplyData {
	agentData?: {
		agentId?: string
	}
	inventoryData?: {
		itemId: string
		folderId: string
		creatorId: string
		ownerId: string
		groupId: string
		baseMask: number
		ownerMask: number
		groupMask: number
		everyoneMask: number
		nextOwnerMask: number
		groupOwned: boolean
		assetId: string
		type: number
		invType: number
		flags: number
		saleType: number
		salePrice: number
		name: string | Buffer
		description: string | Buffer
		creationDate: number
		crc: number
	}[]
}

export const fetchInventoryReplyMetadata = {
	id: 280,
	name: "FetchInventoryReply",
	frequency: 2,
	trusted: true,
	compression: true,
	blocks: [
		{
			name: "agentData",
			parameters: [["agentId", UUID]],
		},
		{
			name: "inventoryData",
			parameters: [
				["itemId", UUID],
				["folderId", UUID],
				["creatorId", UUID],
				["ownerId", UUID],
				["groupId", UUID],
				["baseMask", U32],
				["ownerMask", U32],
				["groupMask", U32],
				["everyoneMask", U32],
				["nextOwnerMask", U32],
				["groupOwned", Bool],
				["assetId", UUID],
				["type", S8],
				["invType", S8],
				["flags", U32],
				["saleType", U8],
				["salePrice", S32],
				["name", Variable1],
				["description", Variable1],
				["creationDate", S32],
				["crc", U32],
			],
			multiple: true,
		},
	],
} satisfies PacketMetadata

export const fetchInventoryReply = createPacketSender<FetchInventoryReplyData>(
	fetchInventoryReplyMetadata,
)

export const createFetchInventoryReplyDelegate =
	createPacketDelegate<FetchInventoryReplyData>(fetchInventoryReplyMetadata)
