/**
 * FindAgent Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { F64, IP, UUID } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface FindAgentData {
	agentBlock?: {
		hunter: string
		prey: string
		spaceIp: IP
	}
	locationBlock?: {
		globalX: number
		globalY: number
	}[]
}

export const findAgentMetadata = {
	id: 256,
	name: "FindAgent",
	frequency: 2,
	blocks: [
		{
			name: "agentBlock",
			parameters: [
				["hunter", UUID],
				["prey", UUID],
				["spaceIp", IP],
			],
		},
		{
			name: "locationBlock",
			parameters: [
				["globalX", F64],
				["globalY", F64],
			],
			multiple: true,
		},
	],
} satisfies PacketMetadata

export const findAgent = createPacketSender<FindAgentData>(findAgentMetadata)

export const createFindAgentDelegate =
	createPacketDelegate<FindAgentData>(findAgentMetadata)
