/**
 * ForceObjectSelect Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { Bool, U32 } from "../types"

export interface ForceObjectSelectData {
	header?: {
		resetList: boolean
	}
	data?: {
		localId: number
	}[]
}

export const forceObjectSelectMetadata = {
	id: 205,
	name: "ForceObjectSelect",
	frequency: 2,
	trusted: true,
	blocks: [
		{
			name: "header",
			parameters: [["resetList", Bool]],
		},
		{
			name: "data",
			parameters: [["localId", U32]],
			multiple: true,
		},
	],
} satisfies PacketMetadata

export const forceObjectSelect = createPacketSender<ForceObjectSelectData>(
	forceObjectSelectMetadata,
)

export const createForceObjectSelectDelegate =
	createPacketDelegate<ForceObjectSelectData>(forceObjectSelectMetadata)
