/**
 * FormFriendship Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { UUID } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface FormFriendshipData {
	agentBlock?: {
		sourceId: string
		destId: string
	}
}

export const formFriendshipMetadata = {
	id: 299,
	name: "FormFriendship",
	frequency: 2,
	trusted: true,
	blocks: [
		{
			name: "agentBlock",
			parameters: [
				["sourceId", UUID],
				["destId", UUID],
			],
		},
	],
} satisfies PacketMetadata

export const formFriendship = createPacketSender<FormFriendshipData>(
	formFriendshipMetadata,
)

export const createFormFriendshipDelegate =
	createPacketDelegate<FormFriendshipData>(formFriendshipMetadata)
