/**
 * FreezeUser Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface FreezeUserData {
	agentData?: {
		agentId?: string | Buffer
		sessionId?: string | Buffer
	}
	data?: {
		targetId: string | Buffer
		flags: number
	}
}

export class FreezeUser extends Packet<FreezeUserData> {
	public static override id = 168
	public static override frequency = 0
	public static override trusted = false
	public static override compression = false

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["agentId", Types.UUID],
					["sessionId", Types.UUID],
				]),
			},
		],
		[
			"data",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["targetId", Types.UUID],
					["flags", Types.U32],
				]),
			},
		],
	])
}
