/**
 * GetScriptRunning Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { UUID } from "../types"

export interface GetScriptRunningData {
	script?: {
		objectId: string
		itemId: string
	}
}

export const getScriptRunningMetadata = {
	id: 243,
	name: "GetScriptRunning",
	frequency: 2,
	blocks: [
		{
			name: "script",
			parameters: [
				["objectId", UUID],
				["itemId", UUID],
			],
		},
	],
} satisfies PacketMetadata

export const getScriptRunning = createPacketSender<GetScriptRunningData>(
	getScriptRunningMetadata,
)

export const createGetScriptRunningDelegate =
	createPacketDelegate<GetScriptRunningData>(getScriptRunningMetadata)
