/**
 * GrantGodlikePowers Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { U8, UUID } from "../types"

export interface GrantGodlikePowersData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	grantData?: {
		godLevel: number
		token: string
	}
}

export const grantGodlikePowersMetadata = {
	id: 258,
	name: "GrantGodlikePowers",
	frequency: 2,
	trusted: true,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
			],
		},
		{
			name: "grantData",
			parameters: [
				["godLevel", U8],
				["token", UUID],
			],
		},
	],
} satisfies PacketMetadata

export const grantGodlikePowers = createPacketSender<GrantGodlikePowersData>(
	grantGodlikePowersMetadata,
)

export const createGrantGodlikePowersDelegate =
	createPacketDelegate<GrantGodlikePowersData>(grantGodlikePowersMetadata)
