/**
 * GroupRoleMembersReply Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface GroupRoleMembersReplyData {
	agentData: {
		agentId?: string | Buffer
		groupId: string | Buffer
		requestId: string | Buffer
		totalPairs: number
	}
	memberData?: {
		roleId: string | Buffer
		memberId: string | Buffer
	}[]
}

export class GroupRoleMembersReply extends Packet<GroupRoleMembersReplyData> {
	public static override id = 374
	public static override frequency = 0
	public static override trusted = true
	public static override compression = false

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["agentId", Types.UUID],
					["groupId", Types.UUID],
					["requestId", Types.UUID],
					["totalPairs", Types.U32],
				]),
			},
		],
		[
			"memberData",
			{
				parameters: new Map<string, Types.Type>([
					["roleId", Types.UUID],
					["memberId", Types.UUID],
				]),
			},
		],
	])
}
