/**
 * GroupVoteHistoryRequest Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { UUID } from "../types"

export interface GroupVoteHistoryRequestData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	groupData?: {
		groupId: string
	}
	transactionData?: {
		transactionId: string
	}
}

export const groupVoteHistoryRequestMetadata = {
	id: 361,
	name: "GroupVoteHistoryRequest",
	frequency: 2,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
			],
		},
		{
			name: "groupData",
			parameters: [["groupId", UUID]],
		},
		{
			name: "transactionData",
			parameters: [["transactionId", UUID]],
		},
	],
} satisfies PacketMetadata

export const groupVoteHistoryRequest =
	createPacketSender<GroupVoteHistoryRequestData>(
		groupVoteHistoryRequestMetadata,
	)

export const createGroupVoteHistoryRequestDelegate =
	createPacketDelegate<GroupVoteHistoryRequestData>(
		groupVoteHistoryRequestMetadata,
	)
