/**
 * GroupActiveProposalsRequest Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { UUID } from "../types"

export interface GroupActiveProposalsRequestData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	groupData?: {
		groupId: string
	}
	transactionData?: {
		transactionId: string
	}
}

export const groupActiveProposalsRequestMetadata = {
	id: 359,
	name: "GroupActiveProposalsRequest",
	frequency: 2,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
			],
		},
		{
			name: "groupData",
			parameters: [["groupId", UUID]],
		},
		{
			name: "transactionData",
			parameters: [["transactionId", UUID]],
		},
	],
} satisfies PacketMetadata

export const groupActiveProposalsRequest =
	createPacketSender<GroupActiveProposalsRequestData>(
		groupActiveProposalsRequestMetadata,
	)

export const createGroupActiveProposalsRequestDelegate =
	createPacketDelegate<GroupActiveProposalsRequestData>(
		groupActiveProposalsRequestMetadata,
	)
