/**
 * GroupAccountSummaryReply Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { S32, UUID, Variable1 } from "../types"

export interface GroupAccountSummaryReplyData {
	agentData: {
		agentId?: string
		groupId: string
	}
	moneyData?: {
		requestId: string
		intervalDays: number
		currentInterval: number
		startDate: string | Buffer
		balance: number
		totalCredits: number
		totalDebits: number
		objectTaxCurrent: number
		lightTaxCurrent: number
		landTaxCurrent: number
		groupTaxCurrent: number
		parcelDirFeeCurrent: number
		objectTaxEstimate: number
		lightTaxEstimate: number
		landTaxEstimate: number
		groupTaxEstimate: number
		parcelDirFeeEstimate: number
		nonExemptMembers: number
		lastTaxDate: string | Buffer
		taxDate: string | Buffer
	}
}

export const groupAccountSummaryReplyMetadata = {
	id: 354,
	name: "GroupAccountSummaryReply",
	frequency: 2,
	trusted: true,
	compression: true,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["groupId", UUID],
			],
		},
		{
			name: "moneyData",
			parameters: [
				["requestId", UUID],
				["intervalDays", S32],
				["currentInterval", S32],
				["startDate", Variable1],
				["balance", S32],
				["totalCredits", S32],
				["totalDebits", S32],
				["objectTaxCurrent", S32],
				["lightTaxCurrent", S32],
				["landTaxCurrent", S32],
				["groupTaxCurrent", S32],
				["parcelDirFeeCurrent", S32],
				["objectTaxEstimate", S32],
				["lightTaxEstimate", S32],
				["landTaxEstimate", S32],
				["groupTaxEstimate", S32],
				["parcelDirFeeEstimate", S32],
				["nonExemptMembers", S32],
				["lastTaxDate", Variable1],
				["taxDate", Variable1],
			],
		},
	],
} satisfies PacketMetadata

export const groupAccountSummaryReply =
	createPacketSender<GroupAccountSummaryReplyData>(
		groupAccountSummaryReplyMetadata,
	)

export const createGroupAccountSummaryReplyDelegate =
	createPacketDelegate<GroupAccountSummaryReplyData>(
		groupAccountSummaryReplyMetadata,
	)
