/**
 * GroupAccountDetailsReply Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface GroupAccountDetailsReplyData {
	agentData: {
		agentId?: string | Buffer
		groupId: string | Buffer
	}
	moneyData?: {
		requestId: string | Buffer
		intervalDays: number
		currentInterval: number
		startDate: string | Buffer
	}
	historyData?: {
		description: string | Buffer
		amount: number
	}[]
}

export class GroupAccountDetailsReply extends Packet<GroupAccountDetailsReplyData> {
	public static override id = 356
	public static override frequency = 0
	public static override trusted = true
	public static override compression = true

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["agentId", Types.UUID],
					["groupId", Types.UUID],
				]),
			},
		],
		[
			"moneyData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["requestId", Types.UUID],
					["intervalDays", Types.S32],
					["currentInterval", Types.S32],
					["startDate", Types.Variable1],
				]),
			},
		],
		[
			"historyData",
			{
				parameters: new Map<string, Types.Type>([
					["description", Types.Variable1],
					["amount", Types.S32],
				]),
			},
		],
	])
}
