/**
 * GroupProposalBallot Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { UUID, Variable1 } from "../types"

export interface GroupProposalBallotData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	proposalData?: {
		proposalId: string
		groupId: string
		voteCast: string | Buffer
	}
}

export const groupProposalBallotMetadata = {
	id: 364,
	name: "GroupProposalBallot",
	frequency: 2,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
			],
		},
		{
			name: "proposalData",
			parameters: [
				["proposalId", UUID],
				["groupId", UUID],
				["voteCast", Variable1],
			],
		},
	],
} satisfies PacketMetadata

export const groupProposalBallot = createPacketSender<GroupProposalBallotData>(
	groupProposalBallotMetadata,
)

export const createGroupProposalBallotDelegate =
	createPacketDelegate<GroupProposalBallotData>(groupProposalBallotMetadata)
