/**
 * GroupNoticeAdd Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface GroupNoticeAddData {
	agentData?: {
		agentId?: string
	}
	messageBlock?: {
		toGroupId: string
		id: string
		dialog: number
		fromAgentName: string | Buffer
		message: string | Buffer
		binaryBucket: string | Buffer
	}
}

export class GroupNoticeAdd extends Packet<GroupNoticeAddData> {
	public static override id = 61
	public static override frequency = 0
	public static override trusted = true
	public static override compression = false

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([["agentId", Types.UUID]]),
			},
		],
		[
			"messageBlock",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["toGroupId", Types.UUID],
					["id", Types.UUID],
					["dialog", Types.U8],
					["fromAgentName", Types.Variable1],
					["message", Types.Variable2],
					["binaryBucket", Types.Variable2],
				]),
			},
		],
	])
}
