/**
 * GroupNoticesListReply Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "~/network/types"
import { Packet } from "./packet"

export interface GroupNoticesListReplyData {
	agentData: {
		agentId?: string
		groupId: string
	}
	data?: {
		noticeId: string
		timestamp: number
		fromName: string | Buffer
		subject: string | Buffer
		hasAttachment: boolean
		assetType: number
	}[]
}

export class GroupNoticesListReply extends Packet<GroupNoticesListReplyData> {
	public static override id = 59
	public static override frequency = 0
	public static override trusted = true
	public static override compression = false

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["agentId", Types.UUID],
					["groupId", Types.UUID],
				]),
			},
		],
		[
			"data",
			{
				parameters: new Map<string, Types.Type>([
					["noticeId", Types.UUID],
					["timestamp", Types.U32],
					["fromName", Types.Variable2],
					["subject", Types.Variable2],
					["hasAttachment", Types.Bool],
					["assetType", Types.U8],
				]),
			},
		],
	])
}
