/**
 * GroupNoticeRequest Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { UUID } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface GroupNoticeRequestData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	data?: {
		groupNoticeId: string
	}
}

export const groupNoticeRequestMetadata = {
	id: 60,
	name: "GroupNoticeRequest",
	frequency: 2,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
			],
		},
		{
			name: "data",
			parameters: [["groupNoticeId", UUID]],
		},
	],
} satisfies PacketMetadata

export const groupNoticeRequest = createPacketSender<GroupNoticeRequestData>(
	groupNoticeRequestMetadata,
)

export const createGroupNoticeRequestDelegate =
	createPacketDelegate<GroupNoticeRequestData>(groupNoticeRequestMetadata)
