/**
 * GroupRoleUpdate Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface GroupRoleUpdateData {
	agentData: {
		agentId?: string
		sessionId?: string
		groupId: string
	}
	roleData?: {
		roleId: string
		name: string | Buffer
		description: string | Buffer
		title: string | Buffer
		powers: number | bigint
		updateType: number
	}[]
}

export class GroupRoleUpdate extends Packet<GroupRoleUpdateData> {
	public static override id = 378
	public static override frequency = 0
	public static override trusted = false
	public static override compression = false

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["agentId", Types.UUID],
					["sessionId", Types.UUID],
					["groupId", Types.UUID],
				]),
			},
		],
		[
			"roleData",
			{
				parameters: new Map<string, Types.Type>([
					["roleId", Types.UUID],
					["name", Types.Variable1],
					["description", Types.Variable1],
					["title", Types.Variable1],
					["powers", Types.U64],
					["updateType", Types.U8],
				]),
			},
		],
	])
}
