/**
 * GroupProposalBallot Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface GroupProposalBallotData {
	agentData?: {
		agentId?: string | Buffer
		sessionId?: string | Buffer
	}
	proposalData?: {
		proposalId: string | Buffer
		groupId: string | Buffer
		voteCast: string | Buffer
	}
}

export class GroupProposalBallot extends Packet<GroupProposalBallotData> {
	public static override id = 364
	public static override frequency = 0
	public static override trusted = false
	public static override compression = false

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["agentId", Types.UUID],
					["sessionId", Types.UUID],
				]),
			},
		],
		[
			"proposalData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["proposalId", Types.UUID],
					["groupId", Types.UUID],
					["voteCast", Types.Variable1],
				]),
			},
		],
	])
}
