/**
 * GroupProfileRequest Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { UUID } from "../types"

export interface GroupProfileRequestData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	groupData?: {
		groupId: string
	}
}

export const groupProfileRequestMetadata = {
	id: 351,
	name: "GroupProfileRequest",
	frequency: 2,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
			],
		},
		{
			name: "groupData",
			parameters: [["groupId", UUID]],
		},
	],
} satisfies PacketMetadata

export const groupProfileRequest = createPacketSender<GroupProfileRequestData>(
	groupProfileRequestMetadata,
)

export const createGroupProfileRequestDelegate =
	createPacketDelegate<GroupProfileRequestData>(groupProfileRequestMetadata)
