/**
 * GroupAccountTransactionsRequest Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface GroupAccountTransactionsRequestData {
	agentData: {
		agentId?: string | Buffer
		sessionId?: string | Buffer
		groupId: string | Buffer
	}
	moneyData?: {
		requestId: string | Buffer
		intervalDays: number
		currentInterval: number
	}
}

export class GroupAccountTransactionsRequest extends Packet<GroupAccountTransactionsRequestData> {
	public static override id = 357
	public static override frequency = 0
	public static override trusted = false
	public static override compression = true

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["agentId", Types.UUID],
					["sessionId", Types.UUID],
					["groupId", Types.UUID],
				]),
			},
		],
		[
			"moneyData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["requestId", Types.UUID],
					["intervalDays", Types.S32],
					["currentInterval", Types.S32],
				]),
			},
		],
	])
}
