/**
 * GroupVoteHistoryItemReply Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "~/network/types"
import { Packet } from "./packet"

export interface GroupVoteHistoryItemReplyData {
	agentData: {
		agentId?: string
		groupId: string
	}
	transactionData?: {
		transactionId: string
		totalNumItems: number
	}
	historyItemData?: {
		voteId: string
		terseDateId: string | Buffer
		startDateTime: string | Buffer
		endDateTime: string | Buffer
		voteInitiator: string
		voteType: string | Buffer
		voteResult: string | Buffer
		majority: number
		quorum: number
		proposalText: string | Buffer
	}
	voteItem?: {
		candidateId: string
		voteCast: string | Buffer
		numVotes: number
	}[]
}

export class GroupVoteHistoryItemReply extends Packet<GroupVoteHistoryItemReplyData> {
	public static override id = 362
	public static override frequency = 0
	public static override trusted = true
	public static override compression = true

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["agentId", Types.UUID],
					["groupId", Types.UUID],
				]),
			},
		],
		[
			"transactionData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["transactionId", Types.UUID],
					["totalNumItems", Types.U32],
				]),
			},
		],
		[
			"historyItemData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["voteId", Types.UUID],
					["terseDateId", Types.Variable1],
					["startDateTime", Types.Variable1],
					["endDateTime", Types.Variable1],
					["voteInitiator", Types.UUID],
					["voteType", Types.Variable1],
					["voteResult", Types.Variable1],
					["majority", Types.F32],
					["quorum", Types.S32],
					["proposalText", Types.Variable2],
				]),
			},
		],
		[
			"voteItem",
			{
				parameters: new Map<string, Types.Type>([
					["candidateId", Types.UUID],
					["voteCast", Types.Variable1],
					["numVotes", Types.S32],
				]),
			},
		],
	])
}
