/**
 * ImagePacket Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { U16, UUID, Variable2 } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface ImagePacketData {
	imageId?: {
		id: string
		packet: number
	}
	imageData?: {
		data: string | Buffer
	}
}

export const imagePacketMetadata = {
	id: 10,
	name: "ImagePacket",
	trusted: true,
	blocks: [
		{
			name: "imageId",
			parameters: [
				["id", UUID],
				["packet", U16],
			],
		},
		{
			name: "imageData",
			parameters: [["data", Variable2]],
		},
	],
} satisfies PacketMetadata

export const imagePacket =
	createPacketSender<ImagePacketData>(imagePacketMetadata)

export const createImagePacketDelegate =
	createPacketDelegate<ImagePacketData>(imagePacketMetadata)
