/**
 * ImageData Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { U8, U16, U32, UUID, Variable2 } from "../types"

export interface ImageDataData {
	imageId?: {
		id: string
		codec: number
		size: number
		packets: number
	}
	imageData?: {
		data: string | Buffer
	}
}

export const imageDataMetadata = {
	id: 9,
	name: "ImageData",
	trusted: true,
	blocks: [
		{
			name: "imageId",
			parameters: [
				["id", UUID],
				["codec", U8],
				["size", U32],
				["packets", U16],
			],
		},
		{
			name: "imageData",
			parameters: [["data", Variable2]],
		},
	],
} satisfies PacketMetadata

export const imageData = createPacketSender<ImageDataData>(imageDataMetadata)

export const createImageDataDelegate =
	createPacketDelegate<ImageDataData>(imageDataMetadata)
