/**
 * ImageData Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface ImageDataData {
	imageId?: {
		id: string
		codec: number
		size: number
		packets: number
	}
	imageData?: {
		data: string | Buffer
	}
}

export class ImageData extends Packet<ImageDataData> {
	public static override id = 9
	public static override frequency = 2
	public static override trusted = true
	public static override compression = false

	public static override format = new Map([
		[
			"imageId",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["id", Types.UUID],
					["codec", Types.U8],
					["size", Types.U32],
					["packets", Types.U16],
				]),
			},
		],
		[
			"imageData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([["data", Types.Variable2]]),
			},
		],
	])
}
