/**
 * InitiateDownload Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { UUID, Variable1 } from "../types"

export interface InitiateDownloadData {
	agentData?: {
		agentId?: string
	}
	fileData?: {
		simFilename: string | Buffer
		viewerFilename: string | Buffer
	}
}

export const initiateDownloadMetadata = {
	id: 403,
	name: "InitiateDownload",
	frequency: 2,
	blocks: [
		{
			name: "agentData",
			parameters: [["agentId", UUID]],
		},
		{
			name: "fileData",
			parameters: [
				["simFilename", Variable1],
				["viewerFilename", Variable1],
			],
		},
	],
} satisfies PacketMetadata

export const initiateDownload = createPacketSender<InitiateDownloadData>(
	initiateDownloadMetadata,
)

export const createInitiateDownloadDelegate =
	createPacketDelegate<InitiateDownloadData>(initiateDownloadMetadata)
