/**
 * InternalScriptMail Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { UUID, Variable1, Variable2 } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface InternalScriptMailData {
	dataBlock?: {
		from: string | Buffer
		to: string
		subject: string | Buffer
		body: string | Buffer
	}
}

export const internalScriptMailMetadata = {
	id: 16,
	name: "InternalScriptMail",
	frequency: 1,
	trusted: true,
	blocks: [
		{
			name: "dataBlock",
			parameters: [
				["from", Variable1],
				["to", UUID],
				["subject", Variable1],
				["body", Variable2],
			],
		},
	],
} satisfies PacketMetadata

export const internalScriptMail = createPacketSender<InternalScriptMailData>(
	internalScriptMailMetadata,
)

export const createInternalScriptMailDelegate =
	createPacketDelegate<InternalScriptMailData>(internalScriptMailMetadata)
