/**
 * InventoryAssetResponse Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { Bool, UUID } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface InventoryAssetResponseData {
	queryData?: {
		queryId: string
		assetId: string
		isReadable: boolean
	}
}

export const inventoryAssetResponseMetadata = {
	id: 283,
	name: "InventoryAssetResponse",
	frequency: 2,
	trusted: true,
	blocks: [
		{
			name: "queryData",
			parameters: [
				["queryId", UUID],
				["assetId", UUID],
				["isReadable", Bool],
			],
		},
	],
} satisfies PacketMetadata

export const inventoryAssetResponse =
	createPacketSender<InventoryAssetResponseData>(inventoryAssetResponseMetadata)

export const createInventoryAssetResponseDelegate =
	createPacketDelegate<InventoryAssetResponseData>(
		inventoryAssetResponseMetadata,
	)
