/**
 * InviteGroupRequest Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "~/network/types"
import { Packet } from "./packet"

export interface InviteGroupRequestData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	groupData?: {
		groupId: string
	}
	inviteData?: {
		inviteeId: string
		roleId: string
	}[]
}

export class InviteGroupRequest extends Packet<InviteGroupRequestData> {
	public static override id = 349
	public static override frequency = 0
	public static override trusted = false
	public static override compression = false

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["agentId", Types.UUID],
					["sessionId", Types.UUID],
				]),
			},
		],
		[
			"groupData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([["groupId", Types.UUID]]),
			},
		],
		[
			"inviteData",
			{
				parameters: new Map<string, Types.Type>([
					["inviteeId", Types.UUID],
					["roleId", Types.UUID],
				]),
			},
		],
	])
}
