/**
 * InviteGroupResponse Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { S32, UUID } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface InviteGroupResponseData {
	inviteData?: {
		agentId: string
		inviteeId: string
		groupId: string
		roleId: string
		membershipFee: number
	}
}

export const inviteGroupResponseMetadata = {
	id: 350,
	name: "InviteGroupResponse",
	frequency: 2,
	trusted: true,
	blocks: [
		{
			name: "inviteData",
			parameters: [
				["agentId", UUID],
				["inviteeId", UUID],
				["groupId", UUID],
				["roleId", UUID],
				["membershipFee", S32],
			],
		},
	],
} satisfies PacketMetadata

export const inviteGroupResponse = createPacketSender<InviteGroupResponseData>(
	inviteGroupResponseMetadata,
)

export const createInviteGroupResponseDelegate =
	createPacketDelegate<InviteGroupResponseData>(inviteGroupResponseMetadata)
