/**
 * JoinGroupRequest Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface JoinGroupRequestData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	groupData?: {
		groupId: string
	}
}

export class JoinGroupRequest extends Packet<JoinGroupRequestData> {
	public static override id = 343
	public static override frequency = 0
	public static override trusted = false
	public static override compression = true

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["agentId", Types.UUID],
					["sessionId", Types.UUID],
				]),
			},
		],
		[
			"groupData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([["groupId", Types.UUID]]),
			},
		],
	])
}
