/**
 * KickUserAck Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { U32, UUID } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface KickUserAckData {
	userInfo?: {
		sessionId: string
		flags: number
	}
}

export const kickUserAckMetadata = {
	id: 164,
	name: "KickUserAck",
	frequency: 2,
	trusted: true,
	blocks: [
		{
			name: "userInfo",
			parameters: [
				["sessionId", UUID],
				["flags", U32],
			],
		},
	],
} satisfies PacketMetadata

export const kickUserAck =
	createPacketSender<KickUserAckData>(kickUserAckMetadata)

export const createKickUserAckDelegate =
	createPacketDelegate<KickUserAckData>(kickUserAckMetadata)
