/**
 * KillChildAgents Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { UUID } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface KillChildAgentsData {
	iDBlock?: {
		agentId: string
	}
}

export const killChildAgentsMetadata = {
	id: 242,
	name: "KillChildAgents",
	frequency: 2,
	trusted: true,
	blocks: [
		{
			name: "iDBlock",
			parameters: [["agentId", UUID]],
		},
	],
} satisfies PacketMetadata

export const killChildAgents = createPacketSender<KillChildAgentsData>(
	killChildAgentsMetadata,
)

export const createKillChildAgentsDelegate =
	createPacketDelegate<KillChildAgentsData>(killChildAgentsMetadata)
