/**
 * LargeGenericMessage Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { UUID, Variable1, Variable2 } from "../types"

export interface LargeGenericMessageData {
	agentData: {
		agentId?: string
		sessionId?: string
		transactionId: string
	}
	methodData?: {
		method: string | Buffer
		invoice: string
	}
	paramList?: {
		parameter: string | Buffer
	}[]
}

export const largeGenericMessageMetadata = {
	id: 430,
	name: "LargeGenericMessage",
	frequency: 2,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
				["transactionId", UUID],
			],
		},
		{
			name: "methodData",
			parameters: [
				["method", Variable1],
				["invoice", UUID],
			],
		},
		{
			name: "paramList",
			parameters: [["parameter", Variable2]],
			multiple: true,
		},
	],
} satisfies PacketMetadata

export const largeGenericMessage = createPacketSender<LargeGenericMessageData>(
	largeGenericMessageMetadata,
)

export const createLargeGenericMessageDelegate =
	createPacketDelegate<LargeGenericMessageData>(largeGenericMessageMetadata)
