/**
 * LargeGenericMessage Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface LargeGenericMessageData {
	agentData: {
		agentId?: string
		sessionId?: string
		transactionId: string
	}
	methodData?: {
		method: string | Buffer
		invoice: string
	}
	paramList?: {
		parameter: string | Buffer
	}[]
}

export class LargeGenericMessage extends Packet<LargeGenericMessageData> {
	public static override id = 430
	public static override frequency = 0
	public static override trusted = false
	public static override compression = false

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["agentId", Types.UUID],
					["sessionId", Types.UUID],
					["transactionId", Types.UUID],
				]),
			},
		],
		[
			"methodData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["method", Types.Variable1],
					["invoice", Types.UUID],
				]),
			},
		],
		[
			"paramList",
			{
				parameters: new Map<string, Types.Type>([
					["parameter", Types.Variable2],
				]),
			},
		],
	])
}
