/**
 * LayerData Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { U8, Variable2 } from "../types"

export interface LayerDataData {
	layerId?: {
		type: number
	}
	layerData?: {
		data: string | Buffer
	}
}

export const layerDataMetadata = {
	id: 11,
	name: "LayerData",
	trusted: true,
	blocks: [
		{
			name: "layerId",
			parameters: [["type", U8]],
		},
		{
			name: "layerData",
			parameters: [["data", Variable2]],
		},
	],
} satisfies PacketMetadata

export const layerData = createPacketSender<LayerDataData>(layerDataMetadata)

export const createLayerDataDelegate =
	createPacketDelegate<LayerDataData>(layerDataMetadata)
