/**
 * LinkInventoryItem Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface LinkInventoryItemData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	inventoryBlock?: {
		callbackId: number
		folderId: string
		transactionId: string
		oldItemId: string
		type: number
		invType: number
		name: string | Buffer
		description: string | Buffer
	}
}

export class LinkInventoryItem extends Packet<LinkInventoryItemData> {
	public static override id = 426
	public static override frequency = 0
	public static override trusted = false
	public static override compression = true

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["agentId", Types.UUID],
					["sessionId", Types.UUID],
				]),
			},
		],
		[
			"inventoryBlock",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["callbackId", Types.U32],
					["folderId", Types.UUID],
					["transactionId", Types.UUID],
					["oldItemId", Types.UUID],
					["type", Types.S8],
					["invType", Types.S8],
					["name", Types.Variable1],
					["description", Types.Variable1],
				]),
			},
		],
	])
}
