/**
 * LinkInventoryItem Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { S8, U32, UUID, Variable1 } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface LinkInventoryItemData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	inventoryBlock?: {
		callbackId: number
		folderId: string
		transactionId: string
		oldItemId: string
		type: number
		invType: number
		name: string | Buffer
		description: string | Buffer
	}
}

export const linkInventoryItemMetadata = {
	id: 426,
	name: "LinkInventoryItem",
	frequency: 2,
	compression: true,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
			],
		},
		{
			name: "inventoryBlock",
			parameters: [
				["callbackId", U32],
				["folderId", UUID],
				["transactionId", UUID],
				["oldItemId", UUID],
				["type", S8],
				["invType", S8],
				["name", Variable1],
				["description", Variable1],
			],
		},
	],
} satisfies PacketMetadata

export const linkInventoryItem = createPacketSender<LinkInventoryItemData>(
	linkInventoryItemMetadata,
)

export const createLinkInventoryItemDelegate =
	createPacketDelegate<LinkInventoryItemData>(linkInventoryItemMetadata)
