/**
 * LiveHelpGroupRequest Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface LiveHelpGroupRequestData {
	requestData?: {
		requestId: string | Buffer
		agentId: string | Buffer
	}
}

export class LiveHelpGroupRequest extends Packet<LiveHelpGroupRequestData> {
	public static override id = 379
	public static override frequency = 0
	public static override trusted = true
	public static override compression = false

	public static override format = new Map([
		[
			"requestData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["requestId", Types.UUID],
					["agentId", Types.UUID],
				]),
			},
		],
	])
}
