/**
 * LoadURL Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface LoadURLData {
	data?: {
		objectName: string | Buffer
		objectId: string | Buffer
		ownerId: string | Buffer
		ownerIsGroup: boolean
		message: string | Buffer
		url: string | Buffer
	}
}

export class LoadURL extends Packet<LoadURLData> {
	public static override id = 194
	public static override frequency = 0
	public static override trusted = true
	public static override compression = false

	public static override format = new Map([
		[
			"data",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["objectName", Types.Variable1],
					["objectId", Types.UUID],
					["ownerId", Types.UUID],
					["ownerIsGroup", Types.Bool],
					["message", Types.Variable1],
					["url", Types.Variable1],
				]),
			},
		],
	])
}
