/**
 * LogDwellTime Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface LogDwellTimeData {
	dwellInfo?: {
		agentId: string
		sessionId: string
		duration: number
		simName: string | Buffer
		regionX: number
		regionY: number
		avgAgentsInView: number
		avgViewerFps: number
	}
}

export class LogDwellTime extends Packet<LogDwellTimeData> {
	public static override id = 18
	public static override frequency = 0
	public static override trusted = true
	public static override compression = false

	public static override format = new Map([
		[
			"dwellInfo",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["agentId", Types.UUID],
					["sessionId", Types.UUID],
					["duration", Types.F32],
					["simName", Types.Variable1],
					["regionX", Types.U32],
					["regionY", Types.U32],
					["avgAgentsInView", Types.U8],
					["avgViewerFps", Types.U8],
				]),
			},
		],
	])
}
