/**
 * LogTextMessage Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface LogTextMessageData {
	dataBlock?: {
		fromAgentId: string
		toAgentId: string
		globalX: number
		globalY: number
		time: number
		message: string | Buffer
	}[]
}

export class LogTextMessage extends Packet<LogTextMessageData> {
	public static override id = 391
	public static override frequency = 0
	public static override trusted = true
	public static override compression = true

	public static override format = new Map([
		[
			"dataBlock",
			{
				parameters: new Map<string, Types.Type>([
					["fromAgentId", Types.UUID],
					["toAgentId", Types.UUID],
					["globalX", Types.F64],
					["globalY", Types.F64],
					["time", Types.U32],
					["message", Types.Variable2],
				]),
			},
		],
	])
}
