/**
 * LogoutReply Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { UUID } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface LogoutReplyData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	inventoryData?: {
		itemId: string
	}[]
}

export const logoutReplyMetadata = {
	id: 253,
	name: "LogoutReply",
	frequency: 2,
	trusted: true,
	compression: true,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
			],
		},
		{
			name: "inventoryData",
			parameters: [["itemId", UUID]],
			multiple: true,
		},
	],
} satisfies PacketMetadata

export const logoutReply =
	createPacketSender<LogoutReplyData>(logoutReplyMetadata)

export const createLogoutReplyDelegate =
	createPacketDelegate<LogoutReplyData>(logoutReplyMetadata)
