/**
 * MapLayerReply Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface MapLayerReplyData {
	agentData?: {
		agentId?: string
		flags?: number
	}
	layerData?: {
		left: number
		right: number
		top: number
		bottom: number
		imageId: string
	}[]
}

export class MapLayerReply extends Packet<MapLayerReplyData> {
	public static override id = 406
	public static override frequency = 0
	public static override trusted = true
	public static override compression = false

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["agentId", Types.UUID],
					["flags", Types.U32],
				]),
			},
		],
		[
			"layerData",
			{
				parameters: new Map<string, Types.Type>([
					["left", Types.U32],
					["right", Types.U32],
					["top", Types.U32],
					["bottom", Types.U32],
					["imageId", Types.UUID],
				]),
			},
		],
	])
}
