/**
 * MapBlockReply Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "~/network/types"
import { Packet } from "./packet"

export interface MapBlockReplyData {
	agentData?: {
		agentId?: string
		flags?: number
	}
	data?: {
		x: number
		y: number
		name: string | Buffer
		access: number
		regionFlags: number
		waterHeight: number
		agents: number
		mapImageId: string
	}[]
}

export class MapBlockReply extends Packet<MapBlockReplyData> {
	public static override id = 409
	public static override frequency = 0
	public static override trusted = true
	public static override compression = false

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["agentId", Types.UUID],
					["flags", Types.U32],
				]),
			},
		],
		[
			"data",
			{
				parameters: new Map<string, Types.Type>([
					["x", Types.U16],
					["y", Types.U16],
					["name", Types.Variable1],
					["access", Types.U8],
					["regionFlags", Types.U32],
					["waterHeight", Types.U8],
					["agents", Types.U8],
					["mapImageId", Types.UUID],
				]),
			},
		],
	])
}
