/**
 * MapLayerReply Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { U32, UUID } from "../types"

export interface MapLayerReplyData {
	agentData?: {
		agentId?: string
		flags?: number
	}
	layerData?: {
		left: number
		right: number
		top: number
		bottom: number
		imageId: string
	}[]
}

export const mapLayerReplyMetadata = {
	id: 406,
	name: "MapLayerReply",
	frequency: 2,
	trusted: true,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["flags", U32],
			],
		},
		{
			name: "layerData",
			parameters: [
				["left", U32],
				["right", U32],
				["top", U32],
				["bottom", U32],
				["imageId", UUID],
			],
			multiple: true,
		},
	],
} satisfies PacketMetadata

export const mapLayerReply = createPacketSender<MapLayerReplyData>(
	mapLayerReplyMetadata,
)

export const createMapLayerReplyDelegate =
	createPacketDelegate<MapLayerReplyData>(mapLayerReplyMetadata)
