/**
 * MapBlockRequest Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface MapBlockRequestData {
	agentData?: {
		agentId?: string | Buffer
		sessionId?: string | Buffer
		flags?: number
		estateId?: number
		godlike?: boolean
	}
	positionData?: {
		minX: number
		maxX: number
		minY: number
		maxY: number
	}
}

export class MapBlockRequest extends Packet<MapBlockRequestData> {
	public static override id = 407
	public static override frequency = 0
	public static override trusted = false
	public static override compression = false

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["agentId", Types.UUID],
					["sessionId", Types.UUID],
					["flags", Types.U32],
					["estateId", Types.U32],
					["godlike", Types.Bool],
				]),
			},
		],
		[
			"positionData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["minX", Types.U16],
					["maxX", Types.U16],
					["minY", Types.U16],
					["maxY", Types.U16],
				]),
			},
		],
	])
}
