/**
 * MapItemRequest Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { Bool, U32, U64, UUID } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface MapItemRequestData {
	agentData?: {
		agentId?: string
		sessionId?: string
		flags?: number
		estateId?: number
		godlike?: boolean
	}
	requestData?: {
		itemType: number
		regionHandle: number | bigint
	}
}

export const mapItemRequestMetadata = {
	id: 410,
	name: "MapItemRequest",
	frequency: 2,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
				["flags", U32],
				["estateId", U32],
				["godlike", Bool],
			],
		},
		{
			name: "requestData",
			parameters: [
				["itemType", U32],
				["regionHandle", U64],
			],
		},
	],
} satisfies PacketMetadata

export const mapItemRequest = createPacketSender<MapItemRequestData>(
	mapItemRequestMetadata,
)

export const createMapItemRequestDelegate =
	createPacketDelegate<MapItemRequestData>(mapItemRequestMetadata)
