/**
 * MapBlockReply Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { U8, U16, U32, UUID, Variable1 } from "../types"

export interface MapBlockReplyData {
	agentData?: {
		agentId?: string
		flags?: number
	}
	data?: {
		x: number
		y: number
		name: string | Buffer
		access: number
		regionFlags: number
		waterHeight: number
		agents: number
		mapImageId: string
	}[]
}

export const mapBlockReplyMetadata = {
	id: 409,
	name: "MapBlockReply",
	frequency: 2,
	trusted: true,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["flags", U32],
			],
		},
		{
			name: "data",
			parameters: [
				["x", U16],
				["y", U16],
				["name", Variable1],
				["access", U8],
				["regionFlags", U32],
				["waterHeight", U8],
				["agents", U8],
				["mapImageId", UUID],
			],
			multiple: true,
		},
	],
} satisfies PacketMetadata

export const mapBlockReply = createPacketSender<MapBlockReplyData>(
	mapBlockReplyMetadata,
)

export const createMapBlockReplyDelegate =
	createPacketDelegate<MapBlockReplyData>(mapBlockReplyMetadata)
