/**
 * MapBlockRequest Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { Bool, U16, U32, UUID } from "../types"

export interface MapBlockRequestData {
	agentData?: {
		agentId?: string
		sessionId?: string
		flags?: number
		estateId?: number
		godlike?: boolean
	}
	positionData?: {
		minX: number
		maxX: number
		minY: number
		maxY: number
	}
}

export const mapBlockRequestMetadata = {
	id: 407,
	name: "MapBlockRequest",
	frequency: 2,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
				["flags", U32],
				["estateId", U32],
				["godlike", Bool],
			],
		},
		{
			name: "positionData",
			parameters: [
				["minX", U16],
				["maxX", U16],
				["minY", U16],
				["maxY", U16],
			],
		},
	],
} satisfies PacketMetadata

export const mapBlockRequest = createPacketSender<MapBlockRequestData>(
	mapBlockRequestMetadata,
)

export const createMapBlockRequestDelegate =
	createPacketDelegate<MapBlockRequestData>(mapBlockRequestMetadata)
