/**
 * MeanCollisionAlert Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface MeanCollisionAlertData {
	meanCollision?: {
		victim: string
		perp: string
		time: number
		mag: number
		type: number
	}[]
}

export class MeanCollisionAlert extends Packet<MeanCollisionAlertData> {
	public static override id = 136
	public static override frequency = 0
	public static override trusted = true
	public static override compression = true

	public static override format = new Map([
		[
			"meanCollision",
			{
				parameters: new Map<string, Types.Type>([
					["victim", Types.UUID],
					["perp", Types.UUID],
					["time", Types.U32],
					["mag", Types.F32],
					["type", Types.U8],
				]),
			},
		],
	])
}
