/**
 * MeanCollisionAlert Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { F32, U8, U32, UUID } from "../types"

export interface MeanCollisionAlertData {
	meanCollision?: {
		victim: string
		perp: string
		time: number
		mag: number
		type: number
	}[]
}

export const meanCollisionAlertMetadata = {
	id: 136,
	name: "MeanCollisionAlert",
	frequency: 2,
	trusted: true,
	compression: true,
	blocks: [
		{
			name: "meanCollision",
			parameters: [
				["victim", UUID],
				["perp", UUID],
				["time", U32],
				["mag", F32],
				["type", U8],
			],
			multiple: true,
		},
	],
} satisfies PacketMetadata

export const meanCollisionAlert = createPacketSender<MeanCollisionAlertData>(
	meanCollisionAlertMetadata,
)

export const createMeanCollisionAlertDelegate =
	createPacketDelegate<MeanCollisionAlertData>(meanCollisionAlertMetadata)
