/**
 * MergeParcel Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface MergeParcelData {
	masterParcelData?: {
		masterId: string | Buffer
	}
	slaveParcelData?: {
		slaveId: string | Buffer
	}[]
}

export class MergeParcel extends Packet<MergeParcelData> {
	public static override id = 223
	public static override frequency = 0
	public static override trusted = true
	public static override compression = false

	public static override format = new Map([
		[
			"masterParcelData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([["masterId", Types.UUID]]),
			},
		],
		[
			"slaveParcelData",
			{
				parameters: new Map<string, Types.Type>([["slaveId", Types.UUID]]),
			},
		],
	])
}
