/**
 * MoneyBalanceRequest Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { UUID } from "../types"

export interface MoneyBalanceRequestData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	moneyData?: {
		transactionId: string
	}
}

export const moneyBalanceRequestMetadata = {
	id: 313,
	name: "MoneyBalanceRequest",
	frequency: 2,
	compression: true,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
			],
		},
		{
			name: "moneyData",
			parameters: [["transactionId", UUID]],
		},
	],
} satisfies PacketMetadata

export const moneyBalanceRequest = createPacketSender<MoneyBalanceRequestData>(
	moneyBalanceRequestMetadata,
)

export const createMoneyBalanceRequestDelegate =
	createPacketDelegate<MoneyBalanceRequestData>(moneyBalanceRequestMetadata)
