/**
 * MoveInventoryItem Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { Bool, UUID, Variable1 } from "../types"

export interface MoveInventoryItemData {
	agentData: {
		agentId?: string
		sessionId?: string
		stamp: boolean
	}
	inventoryData?: {
		itemId: string
		folderId: string
		newName: string | Buffer
	}[]
}

export const moveInventoryItemMetadata = {
	id: 268,
	name: "MoveInventoryItem",
	frequency: 2,
	compression: true,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
				["stamp", Bool],
			],
		},
		{
			name: "inventoryData",
			parameters: [
				["itemId", UUID],
				["folderId", UUID],
				["newName", Variable1],
			],
			multiple: true,
		},
	],
} satisfies PacketMetadata

export const moveInventoryItem = createPacketSender<MoveInventoryItemData>(
	moveInventoryItemMetadata,
)

export const createMoveInventoryItemDelegate =
	createPacketDelegate<MoveInventoryItemData>(moveInventoryItemMetadata)
