/**
 * ObjectPosition Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { U32, UUID, Vector3 } from "../types"

export interface ObjectPositionData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	objectData?: {
		objectLocalId: number
		position: Vector3
	}[]
}

export const objectPositionMetadata = {
	id: 4,
	name: "ObjectPosition",
	frequency: 1,
	compression: true,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
			],
		},
		{
			name: "objectData",
			parameters: [
				["objectLocalId", U32],
				["position", Vector3],
			],
			multiple: true,
		},
	],
} satisfies PacketMetadata

export const objectPosition = createPacketSender<ObjectPositionData>(
	objectPositionMetadata,
)

export const createObjectPositionDelegate =
	createPacketDelegate<ObjectPositionData>(objectPositionMetadata)
