/**
 * ObjectDetach Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { U32, UUID } from "../types"

export interface ObjectDetachData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	objectData?: {
		objectLocalId: number
	}[]
}

export const objectDetachMetadata = {
	id: 113,
	name: "ObjectDetach",
	frequency: 2,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
			],
		},
		{
			name: "objectData",
			parameters: [["objectLocalId", U32]],
			multiple: true,
		},
	],
} satisfies PacketMetadata

export const objectDetach =
	createPacketSender<ObjectDetachData>(objectDetachMetadata)

export const createObjectDetachDelegate =
	createPacketDelegate<ObjectDetachData>(objectDetachMetadata)
