/**
 * ObjectIncludeInSearch Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { Bool, U32, UUID } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface ObjectIncludeInSearchData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	objectData?: {
		objectLocalId: number
		includeInSearch: boolean
	}[]
}

export const objectIncludeInSearchMetadata = {
	id: 424,
	name: "ObjectIncludeInSearch",
	frequency: 2,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
			],
		},
		{
			name: "objectData",
			parameters: [
				["objectLocalId", U32],
				["includeInSearch", Bool],
			],
			multiple: true,
		},
	],
} satisfies PacketMetadata

export const objectIncludeInSearch =
	createPacketSender<ObjectIncludeInSearchData>(objectIncludeInSearchMetadata)

export const createObjectIncludeInSearchDelegate =
	createPacketDelegate<ObjectIncludeInSearchData>(objectIncludeInSearchMetadata)
