/**
 * ObjectCategory Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { U32, UUID } from "../types"

export interface ObjectCategoryData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	objectData?: {
		localId: number
		category: number
	}[]
}

export const objectCategoryMetadata = {
	id: 109,
	name: "ObjectCategory",
	frequency: 2,
	compression: true,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
			],
		},
		{
			name: "objectData",
			parameters: [
				["localId", U32],
				["category", U32],
			],
			multiple: true,
		},
	],
} satisfies PacketMetadata

export const objectCategory = createPacketSender<ObjectCategoryData>(
	objectCategoryMetadata,
)

export const createObjectCategoryDelegate =
	createPacketDelegate<ObjectCategoryData>(objectCategoryMetadata)
