/**
 * ObjectOwner Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface ObjectOwnerData {
	agentData?: {
		agentId?: string | Buffer
		sessionId?: string | Buffer
	}
	headerData?: {
		override: boolean
		ownerId: string | Buffer
		groupId: string | Buffer
	}
	objectData?: {
		objectLocalId: number
	}[]
}

export class ObjectOwner extends Packet<ObjectOwnerData> {
	public static override id = 100
	public static override frequency = 0
	public static override trusted = false
	public static override compression = true

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["agentId", Types.UUID],
					["sessionId", Types.UUID],
				]),
			},
		],
		[
			"headerData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["override", Types.Bool],
					["ownerId", Types.UUID],
					["groupId", Types.UUID],
				]),
			},
		],
		[
			"objectData",
			{
				parameters: new Map<string, Types.Type>([["objectLocalId", Types.U32]]),
			},
		],
	])
}
