/**
 * ObjectName Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface ObjectNameData {
	agentData?: {
		agentId?: string | Buffer
		sessionId?: string | Buffer
	}
	objectData?: {
		localId: number
		name: string | Buffer
	}[]
}

export class ObjectName extends Packet<ObjectNameData> {
	public static override id = 107
	public static override frequency = 0
	public static override trusted = false
	public static override compression = true

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["agentId", Types.UUID],
					["sessionId", Types.UUID],
				]),
			},
		],
		[
			"objectData",
			{
				parameters: new Map<string, Types.Type>([
					["localId", Types.U32],
					["name", Types.Variable1],
				]),
			},
		],
	])
}
