/**
 * ObjectDescription Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { U32, UUID, Variable1 } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface ObjectDescriptionData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	objectData?: {
		localId: number
		description: string | Buffer
	}[]
}

export const objectDescriptionMetadata = {
	id: 108,
	name: "ObjectDescription",
	frequency: 2,
	compression: true,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
			],
		},
		{
			name: "objectData",
			parameters: [
				["localId", U32],
				["description", Variable1],
			],
			multiple: true,
		},
	],
} satisfies PacketMetadata

export const objectDescription = createPacketSender<ObjectDescriptionData>(
	objectDescriptionMetadata,
)

export const createObjectDescriptionDelegate =
	createPacketDelegate<ObjectDescriptionData>(objectDescriptionMetadata)
