/**
 * ObjectSpinStop Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { UUID } from "../types"

export interface ObjectSpinStopData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	objectData?: {
		objectId: string
	}
}

export const objectSpinStopMetadata = {
	id: 122,
	name: "ObjectSpinStop",
	frequency: 2,
	compression: true,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
			],
		},
		{
			name: "objectData",
			parameters: [["objectId", UUID]],
		},
	],
} satisfies PacketMetadata

export const objectSpinStop = createPacketSender<ObjectSpinStopData>(
	objectSpinStopMetadata,
)

export const createObjectSpinStopDelegate =
	createPacketDelegate<ObjectSpinStopData>(objectSpinStopMetadata)
