/**
 * ObjectName Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { U32, UUID, Variable1 } from "../types"

export interface ObjectNameData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	objectData?: {
		localId: number
		name: string | Buffer
	}[]
}

export const objectNameMetadata = {
	id: 107,
	name: "ObjectName",
	frequency: 2,
	compression: true,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
			],
		},
		{
			name: "objectData",
			parameters: [
				["localId", U32],
				["name", Variable1],
			],
			multiple: true,
		},
	],
} satisfies PacketMetadata

export const objectName = createPacketSender<ObjectNameData>(objectNameMetadata)

export const createObjectNameDelegate =
	createPacketDelegate<ObjectNameData>(objectNameMetadata)
