/**
 * ObjectSpinStart Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "~/network/types"
import { Packet } from "./packet"

export interface ObjectSpinStartData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	objectData?: {
		objectId: string
	}
}

export class ObjectSpinStart extends Packet<ObjectSpinStartData> {
	public static override id = 120
	public static override frequency = 0
	public static override trusted = false
	public static override compression = true

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["agentId", Types.UUID],
					["sessionId", Types.UUID],
				]),
			},
		],
		[
			"objectData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([["objectId", Types.UUID]]),
			},
		],
	])
}
