/**
 * ObjectAnimation Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { S32, UUID } from "../types"

export interface ObjectAnimationData {
	sender?: {
		id: string
	}
	animationList?: {
		animId: string
		animSequenceId: number
	}[]
}

export const objectAnimationMetadata = {
	id: 30,
	name: "ObjectAnimation",
	trusted: true,
	blocks: [
		{
			name: "sender",
			parameters: [["id", UUID]],
		},
		{
			name: "animationList",
			parameters: [
				["animId", UUID],
				["animSequenceId", S32],
			],
			multiple: true,
		},
	],
} satisfies PacketMetadata

export const objectAnimation = createPacketSender<ObjectAnimationData>(
	objectAnimationMetadata,
)

export const createObjectAnimationDelegate =
	createPacketDelegate<ObjectAnimationData>(objectAnimationMetadata)
