/**
 * ObjectShape Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { S8, U8, U16, U32, UUID } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface ObjectShapeData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	objectData?: {
		objectLocalId: number
		pathCurve: number
		profileCurve: number
		pathBegin: number
		pathEnd: number
		pathScaleX: number
		pathScaleY: number
		pathShearX: number
		pathShearY: number
		pathTwist: number
		pathTwistBegin: number
		pathRadiusOffset: number
		pathTaperX: number
		pathTaperY: number
		pathRevolutions: number
		pathSkew: number
		profileBegin: number
		profileEnd: number
		profileHollow: number
	}[]
}

export const objectShapeMetadata = {
	id: 98,
	name: "ObjectShape",
	frequency: 2,
	compression: true,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
			],
		},
		{
			name: "objectData",
			parameters: [
				["objectLocalId", U32],
				["pathCurve", U8],
				["profileCurve", U8],
				["pathBegin", U16],
				["pathEnd", U16],
				["pathScaleX", U8],
				["pathScaleY", U8],
				["pathShearX", U8],
				["pathShearY", U8],
				["pathTwist", S8],
				["pathTwistBegin", S8],
				["pathRadiusOffset", S8],
				["pathTaperX", S8],
				["pathTaperY", S8],
				["pathRevolutions", U8],
				["pathSkew", S8],
				["profileBegin", U16],
				["profileEnd", U16],
				["profileHollow", U16],
			],
			multiple: true,
		},
	],
} satisfies PacketMetadata

export const objectShape =
	createPacketSender<ObjectShapeData>(objectShapeMetadata)

export const createObjectShapeDelegate =
	createPacketDelegate<ObjectShapeData>(objectShapeMetadata)
