/**
 * ObjectAnimation Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface ObjectAnimationData {
	sender?: {
		id: string | Buffer
	}
	animationList?: {
		animId: string | Buffer
		animSequenceId: number
	}[]
}

export class ObjectAnimation extends Packet<ObjectAnimationData> {
	public static override id = 30
	public static override frequency = 2
	public static override trusted = true
	public static override compression = false

	public static override format = new Map([
		[
			"sender",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([["id", Types.UUID]]),
			},
		],
		[
			"animationList",
			{
				parameters: new Map<string, Types.Type>([
					["animId", Types.UUID],
					["animSequenceId", Types.S32],
				]),
			},
		],
	])
}
