/**
 * ObjectExtraParams Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { Bool, U16, U32, UUID, Variable1 } from "../types"

export interface ObjectExtraParamsData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	objectData?: {
		objectLocalId: number
		paramType: number
		paramInUse: boolean
		paramSize: number
		paramData: string | Buffer
	}[]
}

export const objectExtraParamsMetadata = {
	id: 99,
	name: "ObjectExtraParams",
	frequency: 2,
	compression: true,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
			],
		},
		{
			name: "objectData",
			parameters: [
				["objectLocalId", U32],
				["paramType", U16],
				["paramInUse", Bool],
				["paramSize", U32],
				["paramData", Variable1],
			],
			multiple: true,
		},
	],
} satisfies PacketMetadata

export const objectExtraParams = createPacketSender<ObjectExtraParamsData>(
	objectExtraParamsMetadata,
)

export const createObjectExtraParamsDelegate =
	createPacketDelegate<ObjectExtraParamsData>(objectExtraParamsMetadata)
