/**
 * ObjectLink Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { U32, UUID } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface ObjectLinkData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	objectData?: {
		objectLocalId: number
	}[]
}

export const objectLinkMetadata = {
	id: 115,
	name: "ObjectLink",
	frequency: 2,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
			],
		},
		{
			name: "objectData",
			parameters: [["objectLocalId", U32]],
			multiple: true,
		},
	],
} satisfies PacketMetadata

export const objectLink = createPacketSender<ObjectLinkData>(objectLinkMetadata)

export const createObjectLinkDelegate =
	createPacketDelegate<ObjectLinkData>(objectLinkMetadata)
