/**
 * ObjectProperties Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "~/network/types"
import { Packet } from "./packet"

export interface ObjectPropertiesData {
	objectData?: {
		objectId: string
		creatorId: string
		ownerId: string
		groupId: string
		creationDate: number | bigint
		baseMask: number
		ownerMask: number
		groupMask: number
		everyoneMask: number
		nextOwnerMask: number
		ownershipCost: number
		saleType: number
		salePrice: number
		aggregatePerms: number
		aggregatePermTextures: number
		aggregatePermTexturesOwner: number
		category: number
		inventorySerial: number
		itemId: string
		folderId: string
		fromTaskId: string
		lastOwnerId: string
		name: string | Buffer
		description: string | Buffer
		touchName: string | Buffer
		sitName: string | Buffer
		textureId: string | Buffer
	}[]
}

export class ObjectProperties extends Packet<ObjectPropertiesData> {
	public static override id = 9
	public static override frequency = 1
	public static override trusted = true
	public static override compression = true

	public static override format = new Map([
		[
			"objectData",
			{
				parameters: new Map<string, Types.Type>([
					["objectId", Types.UUID],
					["creatorId", Types.UUID],
					["ownerId", Types.UUID],
					["groupId", Types.UUID],
					["creationDate", Types.U64],
					["baseMask", Types.U32],
					["ownerMask", Types.U32],
					["groupMask", Types.U32],
					["everyoneMask", Types.U32],
					["nextOwnerMask", Types.U32],
					["ownershipCost", Types.S32],
					["saleType", Types.U8],
					["salePrice", Types.S32],
					["aggregatePerms", Types.U8],
					["aggregatePermTextures", Types.U8],
					["aggregatePermTexturesOwner", Types.U8],
					["category", Types.U32],
					["inventorySerial", Types.S16],
					["itemId", Types.UUID],
					["folderId", Types.UUID],
					["fromTaskId", Types.UUID],
					["lastOwnerId", Types.UUID],
					["name", Types.Variable1],
					["description", Types.Variable1],
					["touchName", Types.Variable1],
					["sitName", Types.Variable1],
					["textureId", Types.Variable1],
				]),
			},
		],
	])
}
