/**
 * ObjectUpdateCached Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface ObjectUpdateCachedData {
	regionData?: {
		regionHandle: number | bigint
		timeDilation: number
	}
	objectData?: {
		id: number
		crc: number
		updateFlags: number
	}[]
}

export class ObjectUpdateCached extends Packet<ObjectUpdateCachedData> {
	public static override id = 14
	public static override frequency = 2
	public static override trusted = true
	public static override compression = false

	public static override format = new Map([
		[
			"regionData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["regionHandle", Types.U64],
					["timeDilation", Types.U16],
				]),
			},
		],
		[
			"objectData",
			{
				parameters: new Map<string, Types.Type>([
					["id", Types.U32],
					["crc", Types.U32],
					["updateFlags", Types.U32],
				]),
			},
		],
	])
}
