/**
 * ObjectSpinUpdate Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { Quaternion, UUID } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface ObjectSpinUpdateData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	objectData?: {
		objectId: string
		rotation: Quaternion
	}
}

export const objectSpinUpdateMetadata = {
	id: 121,
	name: "ObjectSpinUpdate",
	frequency: 2,
	compression: true,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
			],
		},
		{
			name: "objectData",
			parameters: [
				["objectId", UUID],
				["rotation", Quaternion],
			],
		},
	],
} satisfies PacketMetadata

export const objectSpinUpdate = createPacketSender<ObjectSpinUpdateData>(
	objectSpinUpdateMetadata,
)

export const createObjectSpinUpdateDelegate =
	createPacketDelegate<ObjectSpinUpdateData>(objectSpinUpdateMetadata)
