/**
 * ObjectClickAction Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { U8, U32, UUID } from "../types"

export interface ObjectClickActionData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	objectData?: {
		objectLocalId: number
		clickAction: number
	}[]
}

export const objectClickActionMetadata = {
	id: 95,
	name: "ObjectClickAction",
	frequency: 2,
	compression: true,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
			],
		},
		{
			name: "objectData",
			parameters: [
				["objectLocalId", U32],
				["clickAction", U8],
			],
			multiple: true,
		},
	],
} satisfies PacketMetadata

export const objectClickAction = createPacketSender<ObjectClickActionData>(
	objectClickActionMetadata,
)

export const createObjectClickActionDelegate =
	createPacketDelegate<ObjectClickActionData>(objectClickActionMetadata)
