/**
 * ObjectDeGrab Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "~/network/types"
import { Packet } from "./packet"

export interface ObjectDeGrabData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	objectData?: {
		localId: number
	}
	surfaceInfo?: {
		uVCoord: Types.Vector3
		sTCoord: Types.Vector3
		faceIndex: number
		position: Types.Vector3
		normal: Types.Vector3
		binormal: Types.Vector3
	}[]
}

export class ObjectDeGrab extends Packet<ObjectDeGrabData> {
	public static override id = 119
	public static override frequency = 0
	public static override trusted = false
	public static override compression = false

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["agentId", Types.UUID],
					["sessionId", Types.UUID],
				]),
			},
		],
		[
			"objectData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([["localId", Types.U32]]),
			},
		],
		[
			"surfaceInfo",
			{
				parameters: new Map<string, Types.Type>([
					["uVCoord", Types.Vector3],
					["sTCoord", Types.Vector3],
					["faceIndex", Types.S32],
					["position", Types.Vector3],
					["normal", Types.Vector3],
					["binormal", Types.Vector3],
				]),
			},
		],
	])
}
