/**
 * OfferCallingCard Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { UUID } from "../types"

export interface OfferCallingCardData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	agentBlock?: {
		destId: string
		transactionId: string
	}
}

export const offerCallingCardMetadata = {
	id: 301,
	name: "OfferCallingCard",
	frequency: 2,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
			],
		},
		{
			name: "agentBlock",
			parameters: [
				["destId", UUID],
				["transactionId", UUID],
			],
		},
	],
} satisfies PacketMetadata

export const offerCallingCard = createPacketSender<OfferCallingCardData>(
	offerCallingCardMetadata,
)

export const createOfferCallingCardDelegate =
	createPacketDelegate<OfferCallingCardData>(offerCallingCardMetadata)
