/**
 * OfflineNotification Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { UUID } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface OfflineNotificationData {
	agentBlock?: {
		agentId: string
	}[]
}

export const offlineNotificationMetadata = {
	id: 323,
	name: "OfflineNotification",
	frequency: 2,
	trusted: true,
	blocks: [
		{
			name: "agentBlock",
			parameters: [["agentId", UUID]],
			multiple: true,
		},
	],
} satisfies PacketMetadata

export const offlineNotification = createPacketSender<OfflineNotificationData>(
	offlineNotificationMetadata,
)

export const createOfflineNotificationDelegate =
	createPacketDelegate<OfflineNotificationData>(offlineNotificationMetadata)
