/**
 * OnlineNotification Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { UUID } from "../types"

export interface OnlineNotificationData {
	agentBlock?: {
		agentId: string
	}[]
}

export const onlineNotificationMetadata = {
	id: 322,
	name: "OnlineNotification",
	frequency: 2,
	trusted: true,
	blocks: [
		{
			name: "agentBlock",
			parameters: [["agentId", UUID]],
			multiple: true,
		},
	],
} satisfies PacketMetadata

export const onlineNotification = createPacketSender<OnlineNotificationData>(
	onlineNotificationMetadata,
)

export const createOnlineNotificationDelegate =
	createPacketDelegate<OnlineNotificationData>(onlineNotificationMetadata)
