/**
 * PacketAck Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "~/network/types"
import { Packet } from "./packet"

export interface PacketAckData {
	packets?: {
		id: number
	}[]
}

export class PacketAck extends Packet<PacketAckData> {
	public static override id = 4294967291
	public static override frequency = 3
	public static override trusted = false
	public static override compression = false

	public static override format = new Map([
		[
			"packets",
			{
				parameters: new Map<string, Types.Type>([["id", Types.U32]]),
			},
		],
	])
}
