/**
 * PacketAck Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { U32 } from "../types"

export interface PacketAckData {
	packets?: {
		id: number
	}[]
}

export const packetAckMetadata = {
	id: 4294967291,
	name: "PacketAck",
	frequency: 3,
	blocks: [
		{
			name: "packets",
			parameters: [["id", U32]],
			multiple: true,
		},
	],
} satisfies PacketMetadata

export const packetAck = createPacketSender<PacketAckData>(packetAckMetadata)

export const createPacketAckDelegate =
	createPacketDelegate<PacketAckData>(packetAckMetadata)
