/**
 * ParcelOverlay Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { S32, Variable2 } from "../types"

export interface ParcelOverlayData {
	parcelData?: {
		sequenceId: number
		data: string | Buffer
	}
}

export const parcelOverlayMetadata = {
	id: 196,
	name: "ParcelOverlay",
	frequency: 2,
	trusted: true,
	compression: true,
	blocks: [
		{
			name: "parcelData",
			parameters: [
				["sequenceId", S32],
				["data", Variable2],
			],
		},
	],
} satisfies PacketMetadata

export const parcelOverlay = createPacketSender<ParcelOverlayData>(
	parcelOverlayMetadata,
)

export const createParcelOverlayDelegate =
	createPacketDelegate<ParcelOverlayData>(parcelOverlayMetadata)
