/**
 * ParcelAccessListUpdate Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { S32, U32, UUID } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface ParcelAccessListUpdateData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	data?: {
		flags: number
		localId: number
		transactionId: string
		sequenceId: number
		sections: number
	}
	list?: {
		id: string
		time: number
		flags: number
	}[]
}

export const parcelAccessListUpdateMetadata = {
	id: 217,
	name: "ParcelAccessListUpdate",
	frequency: 2,
	compression: true,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
			],
		},
		{
			name: "data",
			parameters: [
				["flags", U32],
				["localId", S32],
				["transactionId", UUID],
				["sequenceId", S32],
				["sections", S32],
			],
		},
		{
			name: "list",
			parameters: [
				["id", UUID],
				["time", S32],
				["flags", U32],
			],
			multiple: true,
		},
	],
} satisfies PacketMetadata

export const parcelAccessListUpdate =
	createPacketSender<ParcelAccessListUpdateData>(parcelAccessListUpdateMetadata)

export const createParcelAccessListUpdateDelegate =
	createPacketDelegate<ParcelAccessListUpdateData>(
		parcelAccessListUpdateMetadata,
	)
