/**
 * ParcelBuy Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface ParcelBuyData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	data?: {
		groupId: string
		isGroupOwned: boolean
		removeContribution: boolean
		localId: number
		final: boolean
	}
	parcelData?: {
		price: number
		area: number
	}
}

export class ParcelBuy extends Packet<ParcelBuyData> {
	public static override id = 213
	public static override frequency = 0
	public static override trusted = false
	public static override compression = true

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["agentId", Types.UUID],
					["sessionId", Types.UUID],
				]),
			},
		],
		[
			"data",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["groupId", Types.UUID],
					["isGroupOwned", Types.Bool],
					["removeContribution", Types.Bool],
					["localId", Types.S32],
					["final", Types.Bool],
				]),
			},
		],
		[
			"parcelData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["price", Types.S32],
					["area", Types.S32],
				]),
			},
		],
	])
}
