/**
 * ParcelGodMarkAsContent Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { S32, UUID } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface ParcelGodMarkAsContentData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	parcelData?: {
		localId: number
	}
}

export const parcelGodMarkAsContentMetadata = {
	id: 227,
	name: "ParcelGodMarkAsContent",
	frequency: 2,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
			],
		},
		{
			name: "parcelData",
			parameters: [["localId", S32]],
		},
	],
} satisfies PacketMetadata

export const parcelGodMarkAsContent =
	createPacketSender<ParcelGodMarkAsContentData>(parcelGodMarkAsContentMetadata)

export const createParcelGodMarkAsContentDelegate =
	createPacketDelegate<ParcelGodMarkAsContentData>(
		parcelGodMarkAsContentMetadata,
	)
