/**
 * ParcelAccessListUpdate Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface ParcelAccessListUpdateData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	data?: {
		flags: number
		localId: number
		transactionId: string
		sequenceId: number
		sections: number
	}
	list?: {
		id: string
		time: number
		flags: number
	}[]
}

export class ParcelAccessListUpdate extends Packet<ParcelAccessListUpdateData> {
	public static override id = 217
	public static override frequency = 0
	public static override trusted = false
	public static override compression = true

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["agentId", Types.UUID],
					["sessionId", Types.UUID],
				]),
			},
		],
		[
			"data",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["flags", Types.U32],
					["localId", Types.S32],
					["transactionId", Types.UUID],
					["sequenceId", Types.S32],
					["sections", Types.S32],
				]),
			},
		],
		[
			"list",
			{
				parameters: new Map<string, Types.Type>([
					["id", Types.UUID],
					["time", Types.S32],
					["flags", Types.U32],
				]),
			},
		],
	])
}
