/**
 * ParcelDivide Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { F32, UUID } from "../types"

export interface ParcelDivideData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	parcelData?: {
		west: number
		south: number
		east: number
		north: number
	}
}

export const parcelDivideMetadata = {
	id: 211,
	name: "ParcelDivide",
	frequency: 2,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
			],
		},
		{
			name: "parcelData",
			parameters: [
				["west", F32],
				["south", F32],
				["east", F32],
				["north", F32],
			],
		},
	],
} satisfies PacketMetadata

export const parcelDivide =
	createPacketSender<ParcelDivideData>(parcelDivideMetadata)

export const createParcelDivideDelegate =
	createPacketDelegate<ParcelDivideData>(parcelDivideMetadata)
