/**
 * ParcelSelectObjects Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { S32, U32, UUID } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface ParcelSelectObjectsData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	parcelData?: {
		localId: number
		returnType: number
	}
	returnIDs?: {
		returnId: string
	}[]
}

export const parcelSelectObjectsMetadata = {
	id: 202,
	name: "ParcelSelectObjects",
	frequency: 2,
	compression: true,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
			],
		},
		{
			name: "parcelData",
			parameters: [
				["localId", S32],
				["returnType", U32],
			],
		},
		{
			name: "returnIDs",
			parameters: [["returnId", UUID]],
			multiple: true,
		},
	],
} satisfies PacketMetadata

export const parcelSelectObjects = createPacketSender<ParcelSelectObjectsData>(
	parcelSelectObjectsMetadata,
)

export const createParcelSelectObjectsDelegate =
	createPacketDelegate<ParcelSelectObjectsData>(parcelSelectObjectsMetadata)
