/**
 * ParcelDwellReply Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface ParcelDwellReplyData {
	agentData?: {
		agentId?: string | Buffer
	}
	data?: {
		localId: number
		parcelId: string | Buffer
		dwell: number
	}
}

export class ParcelDwellReply extends Packet<ParcelDwellReplyData> {
	public static override id = 219
	public static override frequency = 0
	public static override trusted = true
	public static override compression = false

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([["agentId", Types.UUID]]),
			},
		],
		[
			"data",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["localId", Types.S32],
					["parcelId", Types.UUID],
					["dwell", Types.F32],
				]),
			},
		],
	])
}
