/**
 * ParcelInfoRequest Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { UUID } from "../types"

export interface ParcelInfoRequestData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	data?: {
		parcelId: string
	}
}

export const parcelInfoRequestMetadata = {
	id: 54,
	name: "ParcelInfoRequest",
	frequency: 2,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
			],
		},
		{
			name: "data",
			parameters: [["parcelId", UUID]],
		},
	],
} satisfies PacketMetadata

export const parcelInfoRequest = createPacketSender<ParcelInfoRequestData>(
	parcelInfoRequestMetadata,
)

export const createParcelInfoRequestDelegate =
	createPacketDelegate<ParcelInfoRequestData>(parcelInfoRequestMetadata)
