/**
 * ParcelAuctions Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { UUID } from "../types"

export interface ParcelAuctionsData {
	parcelData?: {
		parcelId: string
		winnerId: string
	}[]
}

export const parcelAuctionsMetadata = {
	id: 234,
	name: "ParcelAuctions",
	frequency: 2,
	trusted: true,
	blocks: [
		{
			name: "parcelData",
			parameters: [
				["parcelId", UUID],
				["winnerId", UUID],
			],
			multiple: true,
		},
	],
} satisfies PacketMetadata

export const parcelAuctions = createPacketSender<ParcelAuctionsData>(
	parcelAuctionsMetadata,
)

export const createParcelAuctionsDelegate =
	createPacketDelegate<ParcelAuctionsData>(parcelAuctionsMetadata)
