/**
 * ParcelSales Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { UUID } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface ParcelSalesData {
	parcelData?: {
		parcelId: string
		buyerId: string
	}[]
}

export const parcelSalesMetadata = {
	id: 226,
	name: "ParcelSales",
	frequency: 2,
	trusted: true,
	blocks: [
		{
			name: "parcelData",
			parameters: [
				["parcelId", UUID],
				["buyerId", UUID],
			],
			multiple: true,
		},
	],
} satisfies PacketMetadata

export const parcelSales =
	createPacketSender<ParcelSalesData>(parcelSalesMetadata)

export const createParcelSalesDelegate =
	createPacketDelegate<ParcelSalesData>(parcelSalesMetadata)
