/**
 * ParcelMediaCommandMessage Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { F32, U32 } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface ParcelMediaCommandMessageData {
	commandBlock?: {
		flags: number
		command: number
		time: number
	}
}

export const parcelMediaCommandMessageMetadata = {
	id: 419,
	name: "ParcelMediaCommandMessage",
	frequency: 2,
	trusted: true,
	blocks: [
		{
			name: "commandBlock",
			parameters: [
				["flags", U32],
				["command", U32],
				["time", F32],
			],
		},
	],
} satisfies PacketMetadata

export const parcelMediaCommandMessage =
	createPacketSender<ParcelMediaCommandMessageData>(
		parcelMediaCommandMessageMetadata,
	)

export const createParcelMediaCommandMessageDelegate =
	createPacketDelegate<ParcelMediaCommandMessageData>(
		parcelMediaCommandMessageMetadata,
	)
