/**
 * PickDelete Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { UUID } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface PickDeleteData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	data?: {
		pickId: string
	}
}

export const pickDeleteMetadata = {
	id: 186,
	name: "PickDelete",
	frequency: 2,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
			],
		},
		{
			name: "data",
			parameters: [["pickId", UUID]],
		},
	],
} satisfies PacketMetadata

export const pickDelete = createPacketSender<PickDeleteData>(pickDeleteMetadata)

export const createPickDeleteDelegate =
	createPacketDelegate<PickDeleteData>(pickDeleteMetadata)
