/**
 * PickInfoReply Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface PickInfoReplyData {
	agentData?: {
		agentId?: string | Buffer
	}
	data?: {
		pickId: string | Buffer
		creatorId: string | Buffer
		topPick: boolean
		parcelId: string | Buffer
		name: string | Buffer
		desc: string | Buffer
		snapshotId: string | Buffer
		user: string | Buffer
		originalName: string | Buffer
		simName: string | Buffer
		posGlobal: Types.Vector3D
		sortOrder: number
		enabled: boolean
	}
}

export class PickInfoReply extends Packet<PickInfoReplyData> {
	public static override id = 184
	public static override frequency = 0
	public static override trusted = true
	public static override compression = false

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([["agentId", Types.UUID]]),
			},
		],
		[
			"data",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["pickId", Types.UUID],
					["creatorId", Types.UUID],
					["topPick", Types.Bool],
					["parcelId", Types.UUID],
					["name", Types.Variable1],
					["desc", Types.Variable2],
					["snapshotId", Types.UUID],
					["user", Types.Variable1],
					["originalName", Types.Variable1],
					["simName", Types.Variable1],
					["posGlobal", Types.Vector3D],
					["sortOrder", Types.S32],
					["enabled", Types.Bool],
				]),
			},
		],
	])
}
