/**
 * PreloadSound Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { UUID } from "../types"

export interface PreloadSoundData {
	dataBlock?: {
		objectId: string
		ownerId: string
		soundId: string
	}[]
}

export const preloadSoundMetadata = {
	id: 15,
	name: "PreloadSound",
	frequency: 1,
	trusted: true,
	blocks: [
		{
			name: "dataBlock",
			parameters: [
				["objectId", UUID],
				["ownerId", UUID],
				["soundId", UUID],
			],
			multiple: true,
		},
	],
} satisfies PacketMetadata

export const preloadSound =
	createPacketSender<PreloadSoundData>(preloadSoundMetadata)

export const createPreloadSoundDelegate =
	createPacketDelegate<PreloadSoundData>(preloadSoundMetadata)
