/**
 * PreloadSound Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface PreloadSoundData {
	dataBlock?: {
		objectId: string
		ownerId: string
		soundId: string
	}[]
}

export class PreloadSound extends Packet<PreloadSoundData> {
	public static override id = 15
	public static override frequency = 1
	public static override trusted = true
	public static override compression = false

	public static override format = new Map([
		[
			"dataBlock",
			{
				parameters: new Map<string, Types.Type>([
					["objectId", Types.UUID],
					["ownerId", Types.UUID],
					["soundId", Types.UUID],
				]),
			},
		],
	])
}
