/**
 * PurgeInventoryDescendents Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { UUID } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface PurgeInventoryDescendentsData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	inventoryData?: {
		folderId: string
	}
}

export const purgeInventoryDescendentsMetadata = {
	id: 285,
	name: "PurgeInventoryDescendents",
	frequency: 2,
	compression: true,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
			],
		},
		{
			name: "inventoryData",
			parameters: [["folderId", UUID]],
		},
	],
} satisfies PacketMetadata

export const purgeInventoryDescendents =
	createPacketSender<PurgeInventoryDescendentsData>(
		purgeInventoryDescendentsMetadata,
	)

export const createPurgeInventoryDescendentsDelegate =
	createPacketDelegate<PurgeInventoryDescendentsData>(
		purgeInventoryDescendentsMetadata,
	)
