/**
 * Redo Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { UUID } from "../types"

export interface RedoData {
	agentData: {
		agentId?: string
		sessionId?: string
		groupId: string
	}
	objectData?: {
		objectId: string
	}[]
}

export const redoMetadata = {
	id: 76,
	name: "Redo",
	frequency: 2,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
				["groupId", UUID],
			],
		},
		{
			name: "objectData",
			parameters: [["objectId", UUID]],
			multiple: true,
		},
	],
} satisfies PacketMetadata

export const redo = createPacketSender<RedoData>(redoMetadata)

export const createRedoDelegate = createPacketDelegate<RedoData>(redoMetadata)
