/**
 * RegionIDAndHandleReply Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "~/network/types"
import { Packet } from "./packet"

export interface RegionIDAndHandleReplyData {
	replyBlock?: {
		regionId: string
		regionHandle: number | bigint
	}
}

export class RegionIDAndHandleReply extends Packet<RegionIDAndHandleReplyData> {
	public static override id = 310
	public static override frequency = 0
	public static override trusted = true
	public static override compression = false

	public static override format = new Map([
		[
			"replyBlock",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["regionId", Types.UUID],
					["regionHandle", Types.U64],
				]),
			},
		],
	])
}
