/**
 * RegionIDAndHandleReply Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { U64, UUID } from "../types"

export interface RegionIDAndHandleReplyData {
	replyBlock?: {
		regionId: string
		regionHandle: number | bigint
	}
}

export const regionIdAndHandleReplyMetadata = {
	id: 310,
	name: "RegionIDAndHandleReply",
	frequency: 2,
	trusted: true,
	blocks: [
		{
			name: "replyBlock",
			parameters: [
				["regionId", UUID],
				["regionHandle", U64],
			],
		},
	],
} satisfies PacketMetadata

export const regionIdAndHandleReply =
	createPacketSender<RegionIDAndHandleReplyData>(regionIdAndHandleReplyMetadata)

export const createRegionIDAndHandleReplyDelegate =
	createPacketDelegate<RegionIDAndHandleReplyData>(
		regionIdAndHandleReplyMetadata,
	)
