/**
 * RegionHandleRequest Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { UUID } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface RegionHandleRequestData {
	requestBlock?: {
		regionId: string
	}
}

export const regionHandleRequestMetadata = {
	id: 309,
	name: "RegionHandleRequest",
	frequency: 2,
	blocks: [
		{
			name: "requestBlock",
			parameters: [["regionId", UUID]],
		},
	],
} satisfies PacketMetadata

export const regionHandleRequest = createPacketSender<RegionHandleRequestData>(
	regionHandleRequestMetadata,
)

export const createRegionHandleRequestDelegate =
	createPacketDelegate<RegionHandleRequestData>(regionHandleRequestMetadata)
