/**
 * RemoveNameValuePair Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface RemoveNameValuePairData {
	taskData?: {
		id: string | Buffer
	}
	nameValueData?: {
		nVPair: string | Buffer
	}[]
}

export class RemoveNameValuePair extends Packet<RemoveNameValuePairData> {
	public static override id = 330
	public static override frequency = 0
	public static override trusted = true
	public static override compression = false

	public static override format = new Map([
		[
			"taskData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([["id", Types.UUID]]),
			},
		],
		[
			"nameValueData",
			{
				parameters: new Map<string, Types.Type>([["nVPair", Types.Variable2]]),
			},
		],
	])
}
