/**
 * RemoveTaskInventory Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "~/network/types"
import { Packet } from "./packet"

export interface RemoveTaskInventoryData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	inventoryData?: {
		localId: number
		itemId: string
	}
}

export class RemoveTaskInventory extends Packet<RemoveTaskInventoryData> {
	public static override id = 287
	public static override frequency = 0
	public static override trusted = false
	public static override compression = true

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["agentId", Types.UUID],
					["sessionId", Types.UUID],
				]),
			},
		],
		[
			"inventoryData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["localId", Types.U32],
					["itemId", Types.UUID],
				]),
			},
		],
	])
}
