/**
 * RemoveAttachment Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { U8, UUID } from "../types"

export interface RemoveAttachmentData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	attachmentBlock?: {
		attachmentPoint: number
		itemId: string
	}
}

export const removeAttachmentMetadata = {
	id: 332,
	name: "RemoveAttachment",
	frequency: 2,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
			],
		},
		{
			name: "attachmentBlock",
			parameters: [
				["attachmentPoint", U8],
				["itemId", UUID],
			],
		},
	],
} satisfies PacketMetadata

export const removeAttachment = createPacketSender<RemoveAttachmentData>(
	removeAttachmentMetadata,
)

export const createRemoveAttachmentDelegate =
	createPacketDelegate<RemoveAttachmentData>(removeAttachmentMetadata)
