/**
 * RequestGodlikePowers Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { Bool, UUID } from "../types"

export interface RequestGodlikePowersData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	requestBlock?: {
		godlike: boolean
		token: string
	}
}

export const requestGodlikePowersMetadata = {
	id: 257,
	name: "RequestGodlikePowers",
	frequency: 2,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
			],
		},
		{
			name: "requestBlock",
			parameters: [
				["godlike", Bool],
				["token", UUID],
			],
		},
	],
} satisfies PacketMetadata

export const requestGodlikePowers =
	createPacketSender<RequestGodlikePowersData>(requestGodlikePowersMetadata)

export const createRequestGodlikePowersDelegate =
	createPacketDelegate<RequestGodlikePowersData>(requestGodlikePowersMetadata)
