/**
 * RequestXfer Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "~/network/types"
import { Packet } from "./packet"

export interface RequestXferData {
	xferId?: {
		id: number | bigint
		filename: string | Buffer
		filePath: number
		deleteOnCompletion: boolean
		useBigPackets: boolean
		vFileId: string
		vFileType: number
	}
}

export class RequestXfer extends Packet<RequestXferData> {
	public static override id = 156
	public static override frequency = 0
	public static override trusted = false
	public static override compression = true

	public static override format = new Map([
		[
			"xferId",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["id", Types.U64],
					["filename", Types.Variable1],
					["filePath", Types.U8],
					["deleteOnCompletion", Types.Bool],
					["useBigPackets", Types.Bool],
					["vFileId", Types.UUID],
					["vFileType", Types.S16],
				]),
			},
		],
	])
}
