/**
 * RequestInventoryAsset Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface RequestInventoryAssetData {
	queryData?: {
		queryId: string | Buffer
		agentId: string | Buffer
		ownerId: string | Buffer
		itemId: string | Buffer
	}
}

export class RequestInventoryAsset extends Packet<RequestInventoryAssetData> {
	public static override id = 282
	public static override frequency = 0
	public static override trusted = true
	public static override compression = false

	public static override format = new Map([
		[
			"queryData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["queryId", Types.UUID],
					["agentId", Types.UUID],
					["ownerId", Types.UUID],
					["itemId", Types.UUID],
				]),
			},
		],
	])
}
