/**
 * RequestMultipleObjects Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { U8, U32, UUID } from "../types"

export interface RequestMultipleObjectsData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	objectData?: {
		cacheMissType: number
		id: number
	}[]
}

export const requestMultipleObjectsMetadata = {
	id: 3,
	name: "RequestMultipleObjects",
	frequency: 1,
	compression: true,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
			],
		},
		{
			name: "objectData",
			parameters: [
				["cacheMissType", U8],
				["id", U32],
			],
			multiple: true,
		},
	],
} satisfies PacketMetadata

export const requestMultipleObjects =
	createPacketSender<RequestMultipleObjectsData>(requestMultipleObjectsMetadata)

export const createRequestMultipleObjectsDelegate =
	createPacketDelegate<RequestMultipleObjectsData>(
		requestMultipleObjectsMetadata,
	)
