/**
 * RequestTrustedCircuit Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"

export type RequestTrustedCircuitData = Record<string, never>

export const requestTrustedCircuitMetadata = {
	id: 394,
	name: "RequestTrustedCircuit",
	frequency: 2,
	trusted: true,
} satisfies PacketMetadata

export const requestTrustedCircuit =
	createPacketSender<RequestTrustedCircuitData>(requestTrustedCircuitMetadata)

export const createRequestTrustedCircuitDelegate =
	createPacketDelegate<RequestTrustedCircuitData>(requestTrustedCircuitMetadata)
