/**
 * RequestTaskInventory Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { U32, UUID } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface RequestTaskInventoryData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	inventoryData?: {
		localId: number
	}
}

export const requestTaskInventoryMetadata = {
	id: 289,
	name: "RequestTaskInventory",
	frequency: 2,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
			],
		},
		{
			name: "inventoryData",
			parameters: [["localId", U32]],
		},
	],
} satisfies PacketMetadata

export const requestTaskInventory =
	createPacketSender<RequestTaskInventoryData>(requestTaskInventoryMetadata)

export const createRequestTaskInventoryDelegate =
	createPacketDelegate<RequestTaskInventoryData>(requestTaskInventoryMetadata)
