/**
 * RequestPayPrice Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface RequestPayPriceData {
	objectData?: {
		objectId: string
	}
}

export class RequestPayPrice extends Packet<RequestPayPriceData> {
	public static override id = 161
	public static override frequency = 0
	public static override trusted = false
	public static override compression = false

	public static override format = new Map([
		[
			"objectData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([["objectId", Types.UUID]]),
			},
		],
	])
}
