/**
 * RevokePermissions Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { U32, UUID } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface RevokePermissionsData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	data?: {
		objectId: string
		objectPermissions: number
	}
}

export const revokePermissionsMetadata = {
	id: 193,
	name: "RevokePermissions",
	frequency: 2,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
			],
		},
		{
			name: "data",
			parameters: [
				["objectId", UUID],
				["objectPermissions", U32],
			],
		},
	],
} satisfies PacketMetadata

export const revokePermissions = createPacketSender<RevokePermissionsData>(
	revokePermissionsMetadata,
)

export const createRevokePermissionsDelegate =
	createPacketDelegate<RevokePermissionsData>(revokePermissionsMetadata)
