/**
 * RezRestoreToWorld Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface RezRestoreToWorldData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	inventoryData?: {
		itemId: string
		folderId: string
		creatorId: string
		ownerId: string
		groupId: string
		baseMask: number
		ownerMask: number
		groupMask: number
		everyoneMask: number
		nextOwnerMask: number
		groupOwned: boolean
		transactionId: string
		type: number
		invType: number
		flags: number
		saleType: number
		salePrice: number
		name: string | Buffer
		description: string | Buffer
		creationDate: number
		crc: number
	}
}

export class RezRestoreToWorld extends Packet<RezRestoreToWorldData> {
	public static override id = 425
	public static override frequency = 0
	public static override trusted = false
	public static override compression = false

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["agentId", Types.UUID],
					["sessionId", Types.UUID],
				]),
			},
		],
		[
			"inventoryData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["itemId", Types.UUID],
					["folderId", Types.UUID],
					["creatorId", Types.UUID],
					["ownerId", Types.UUID],
					["groupId", Types.UUID],
					["baseMask", Types.U32],
					["ownerMask", Types.U32],
					["groupMask", Types.U32],
					["everyoneMask", Types.U32],
					["nextOwnerMask", Types.U32],
					["groupOwned", Types.Bool],
					["transactionId", Types.UUID],
					["type", Types.S8],
					["invType", Types.S8],
					["flags", Types.U32],
					["saleType", Types.U8],
					["salePrice", Types.S32],
					["name", Types.Variable1],
					["description", Types.Variable1],
					["creationDate", Types.S32],
					["crc", Types.U32],
				]),
			},
		],
	])
}
