/**
 * RezSingleAttachmentFromInv Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { U8, U32, UUID, Variable1 } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface RezSingleAttachmentFromInvData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	objectData?: {
		itemId: string
		ownerId: string
		attachmentPt: number
		itemFlags: number
		groupMask: number
		everyoneMask: number
		nextOwnerMask: number
		name: string | Buffer
		description: string | Buffer
	}
}

export const rezSingleAttachmentFromInvMetadata = {
	id: 395,
	name: "RezSingleAttachmentFromInv",
	frequency: 2,
	compression: true,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
			],
		},
		{
			name: "objectData",
			parameters: [
				["itemId", UUID],
				["ownerId", UUID],
				["attachmentPt", U8],
				["itemFlags", U32],
				["groupMask", U32],
				["everyoneMask", U32],
				["nextOwnerMask", U32],
				["name", Variable1],
				["description", Variable1],
			],
		},
	],
} satisfies PacketMetadata

export const rezSingleAttachmentFromInv =
	createPacketSender<RezSingleAttachmentFromInvData>(
		rezSingleAttachmentFromInvMetadata,
	)

export const createRezSingleAttachmentFromInvDelegate =
	createPacketDelegate<RezSingleAttachmentFromInvData>(
		rezSingleAttachmentFromInvMetadata,
	)
