/**
 * RpcChannelRequest Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { U32, UUID } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface RpcChannelRequestData {
	dataBlock?: {
		gridX: number
		gridY: number
		taskId: string
		itemId: string
	}
}

export const rpcChannelRequestMetadata = {
	id: 413,
	name: "RpcChannelRequest",
	frequency: 2,
	trusted: true,
	blocks: [
		{
			name: "dataBlock",
			parameters: [
				["gridX", U32],
				["gridY", U32],
				["taskId", UUID],
				["itemId", UUID],
			],
		},
	],
} satisfies PacketMetadata

export const rpcChannelRequest = createPacketSender<RpcChannelRequestData>(
	rpcChannelRequestMetadata,
)

export const createRpcChannelRequestDelegate =
	createPacketDelegate<RpcChannelRequestData>(rpcChannelRequestMetadata)
