/**
 * RpcScriptRequestInboundForward Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { IP, Port, U32, UUID, Variable2 } from "../types"

export interface RpcScriptRequestInboundForwardData {
	dataBlock?: {
		rpcServerIp: IP
		rpcServerPort: Port
		taskId: string
		itemId: string
		channelId: string
		intValue: number
		stringValue: string | Buffer
	}
}

export const rpcScriptRequestInboundForwardMetadata = {
	id: 416,
	name: "RpcScriptRequestInboundForward",
	frequency: 2,
	trusted: true,
	blocks: [
		{
			name: "dataBlock",
			parameters: [
				["rpcServerIp", IP],
				["rpcServerPort", Port],
				["taskId", UUID],
				["itemId", UUID],
				["channelId", UUID],
				["intValue", U32],
				["stringValue", Variable2],
			],
		},
	],
} satisfies PacketMetadata

export const rpcScriptRequestInboundForward =
	createPacketSender<RpcScriptRequestInboundForwardData>(
		rpcScriptRequestInboundForwardMetadata,
	)

export const createRpcScriptRequestInboundForwardDelegate =
	createPacketDelegate<RpcScriptRequestInboundForwardData>(
		rpcScriptRequestInboundForwardMetadata,
	)
