/**
 * RpcScriptRequestInbound Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { U32, UUID, Variable2 } from "../types"

export interface RpcScriptRequestInboundData {
	targetBlock?: {
		gridX: number
		gridY: number
	}
	dataBlock?: {
		taskId: string
		itemId: string
		channelId: string
		intValue: number
		stringValue: string | Buffer
	}
}

export const rpcScriptRequestInboundMetadata = {
	id: 415,
	name: "RpcScriptRequestInbound",
	frequency: 2,
	blocks: [
		{
			name: "targetBlock",
			parameters: [
				["gridX", U32],
				["gridY", U32],
			],
		},
		{
			name: "dataBlock",
			parameters: [
				["taskId", UUID],
				["itemId", UUID],
				["channelId", UUID],
				["intValue", U32],
				["stringValue", Variable2],
			],
		},
	],
} satisfies PacketMetadata

export const rpcScriptRequestInbound =
	createPacketSender<RpcScriptRequestInboundData>(
		rpcScriptRequestInboundMetadata,
	)

export const createRpcScriptRequestInboundDelegate =
	createPacketDelegate<RpcScriptRequestInboundData>(
		rpcScriptRequestInboundMetadata,
	)
