/**
 * SaveAssetIntoInventory Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { UUID } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface SaveAssetIntoInventoryData {
	agentData?: {
		agentId?: string
	}
	inventoryData?: {
		itemId: string
		newAssetId: string
	}
}

export const saveAssetIntoInventoryMetadata = {
	id: 272,
	name: "SaveAssetIntoInventory",
	frequency: 2,
	trusted: true,
	blocks: [
		{
			name: "agentData",
			parameters: [["agentId", UUID]],
		},
		{
			name: "inventoryData",
			parameters: [
				["itemId", UUID],
				["newAssetId", UUID],
			],
		},
	],
} satisfies PacketMetadata

export const saveAssetIntoInventory =
	createPacketSender<SaveAssetIntoInventoryData>(saveAssetIntoInventoryMetadata)

export const createSaveAssetIntoInventoryDelegate =
	createPacketDelegate<SaveAssetIntoInventoryData>(
		saveAssetIntoInventoryMetadata,
	)
