/**
 * ScriptAnswerYes Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { S32, UUID } from "../types"

export interface ScriptAnswerYesData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	data?: {
		taskId: string
		itemId: string
		questions: number
	}
}

export const scriptAnswerYesMetadata = {
	id: 132,
	name: "ScriptAnswerYes",
	frequency: 2,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
			],
		},
		{
			name: "data",
			parameters: [
				["taskId", UUID],
				["itemId", UUID],
				["questions", S32],
			],
		},
	],
} satisfies PacketMetadata

export const scriptAnswerYes = createPacketSender<ScriptAnswerYesData>(
	scriptAnswerYesMetadata,
)

export const createScriptAnswerYesDelegate =
	createPacketDelegate<ScriptAnswerYesData>(scriptAnswerYesMetadata)
