/**
 * ScriptDataRequest Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface ScriptDataRequestData {
	dataBlock?: {
		hash: number | bigint
		requestType: number
		request: string | Buffer
	}[]
}

export class ScriptDataRequest extends Packet<ScriptDataRequestData> {
	public static override id = 337
	public static override frequency = 0
	public static override trusted = true
	public static override compression = false

	public static override format = new Map([
		[
			"dataBlock",
			{
				parameters: new Map<string, Types.Type>([
					["hash", Types.U64],
					["requestType", Types.S8],
					["request", Types.Variable2],
				]),
			},
		],
	])
}
