/**
 * ScriptAnswerYes Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "~/network/types"
import { Packet } from "./packet"

export interface ScriptAnswerYesData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	data?: {
		taskId: string
		itemId: string
		questions: number
	}
}

export class ScriptAnswerYes extends Packet<ScriptAnswerYesData> {
	public static override id = 132
	public static override frequency = 0
	public static override trusted = false
	public static override compression = false

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["agentId", Types.UUID],
					["sessionId", Types.UUID],
				]),
			},
		],
		[
			"data",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["taskId", Types.UUID],
					["itemId", Types.UUID],
					["questions", Types.S32],
				]),
			},
		],
	])
}
