/**
 * ScriptControlChange Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface ScriptControlChangeData {
	data?: {
		takeControls: boolean
		controls: number
		passToAgent: boolean
	}[]
}

export class ScriptControlChange extends Packet<ScriptControlChangeData> {
	public static override id = 189
	public static override frequency = 0
	public static override trusted = true
	public static override compression = false

	public static override format = new Map([
		[
			"data",
			{
				parameters: new Map<string, Types.Type>([
					["takeControls", Types.Bool],
					["controls", Types.U32],
					["passToAgent", Types.Bool],
				]),
			},
		],
	])
}
