/**
 * ScriptReset Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { UUID } from "../types"

export interface ScriptResetData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	script?: {
		objectId: string
		itemId: string
	}
}

export const scriptResetMetadata = {
	id: 246,
	name: "ScriptReset",
	frequency: 2,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
			],
		},
		{
			name: "script",
			parameters: [
				["objectId", UUID],
				["itemId", UUID],
			],
		},
	],
} satisfies PacketMetadata

export const scriptReset =
	createPacketSender<ScriptResetData>(scriptResetMetadata)

export const createScriptResetDelegate =
	createPacketDelegate<ScriptResetData>(scriptResetMetadata)
