/**
 * ScriptControlChange Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { Bool, U32 } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface ScriptControlChangeData {
	data?: {
		takeControls: boolean
		controls: number
		passToAgent: boolean
	}[]
}

export const scriptControlChangeMetadata = {
	id: 189,
	name: "ScriptControlChange",
	frequency: 2,
	trusted: true,
	blocks: [
		{
			name: "data",
			parameters: [
				["takeControls", Bool],
				["controls", U32],
				["passToAgent", Bool],
			],
			multiple: true,
		},
	],
} satisfies PacketMetadata

export const scriptControlChange = createPacketSender<ScriptControlChangeData>(
	scriptControlChangeMetadata,
)

export const createScriptControlChangeDelegate =
	createPacketDelegate<ScriptControlChangeData>(scriptControlChangeMetadata)
