/**
 * ScriptQuestion Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface ScriptQuestionData {
	data?: {
		taskId: string
		itemId: string
		objectName: string | Buffer
		objectOwner: string | Buffer
		questions: number
	}
	experience?: {
		experienceId: string
	}
}

export class ScriptQuestion extends Packet<ScriptQuestionData> {
	public static override id = 188
	public static override frequency = 0
	public static override trusted = true
	public static override compression = false

	public static override format = new Map([
		[
			"data",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["taskId", Types.UUID],
					["itemId", Types.UUID],
					["objectName", Types.Variable1],
					["objectOwner", Types.Variable1],
					["questions", Types.S32],
				]),
			},
		],
		[
			"experience",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([["experienceId", Types.UUID]]),
			},
		],
	])
}
