/**
 * ScriptDialogReply Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { S32, UUID, Variable1 } from "../types"

export interface ScriptDialogReplyData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	data?: {
		objectId: string
		chatChannel: number
		buttonIndex: number
		buttonLabel: string | Buffer
	}
}

export const scriptDialogReplyMetadata = {
	id: 191,
	name: "ScriptDialogReply",
	frequency: 2,
	compression: true,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
			],
		},
		{
			name: "data",
			parameters: [
				["objectId", UUID],
				["chatChannel", S32],
				["buttonIndex", S32],
				["buttonLabel", Variable1],
			],
		},
	],
} satisfies PacketMetadata

export const scriptDialogReply = createPacketSender<ScriptDialogReplyData>(
	scriptDialogReplyMetadata,
)

export const createScriptDialogReplyDelegate =
	createPacketDelegate<ScriptDialogReplyData>(scriptDialogReplyMetadata)
