/**
 * ScriptSensorRequest Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import {
	F32,
	Quaternion,
	S32,
	U8,
	U64,
	UUID,
	Variable1,
	Vector3,
} from "../types"

export interface ScriptSensorRequestData {
	requester?: {
		sourceId: string
		requestId: string
		searchId: string
		searchPos: Vector3
		searchDir: Quaternion
		searchName: string | Buffer
		type: number
		range: number
		arc: number
		regionHandle: number | bigint
		searchRegions: number
	}
}

export const scriptSensorRequestMetadata = {
	id: 247,
	name: "ScriptSensorRequest",
	frequency: 2,
	trusted: true,
	compression: true,
	blocks: [
		{
			name: "requester",
			parameters: [
				["sourceId", UUID],
				["requestId", UUID],
				["searchId", UUID],
				["searchPos", Vector3],
				["searchDir", Quaternion],
				["searchName", Variable1],
				["type", S32],
				["range", F32],
				["arc", F32],
				["regionHandle", U64],
				["searchRegions", U8],
			],
		},
	],
} satisfies PacketMetadata

export const scriptSensorRequest = createPacketSender<ScriptSensorRequestData>(
	scriptSensorRequestMetadata,
)

export const createScriptSensorRequestDelegate =
	createPacketDelegate<ScriptSensorRequestData>(scriptSensorRequestMetadata)
