/**
 * ScriptMailRegistration Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { Port, U32, UUID, Variable1 } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface ScriptMailRegistrationData {
	dataBlock?: {
		targetIp: string | Buffer
		targetPort: Port
		taskId: string
		flags: number
	}
}

export const scriptMailRegistrationMetadata = {
	id: 418,
	name: "ScriptMailRegistration",
	frequency: 2,
	trusted: true,
	blocks: [
		{
			name: "dataBlock",
			parameters: [
				["targetIp", Variable1],
				["targetPort", Port],
				["taskId", UUID],
				["flags", U32],
			],
		},
	],
} satisfies PacketMetadata

export const scriptMailRegistration =
	createPacketSender<ScriptMailRegistrationData>(scriptMailRegistrationMetadata)

export const createScriptMailRegistrationDelegate =
	createPacketDelegate<ScriptMailRegistrationData>(
		scriptMailRegistrationMetadata,
	)
