/**
 * ScriptDataReply Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { U64, Variable2 } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface ScriptDataReplyData {
	dataBlock?: {
		hash: number | bigint
		reply: string | Buffer
	}[]
}

export const scriptDataReplyMetadata = {
	id: 338,
	name: "ScriptDataReply",
	frequency: 2,
	trusted: true,
	blocks: [
		{
			name: "dataBlock",
			parameters: [
				["hash", U64],
				["reply", Variable2],
			],
			multiple: true,
		},
	],
} satisfies PacketMetadata

export const scriptDataReply = createPacketSender<ScriptDataReplyData>(
	scriptDataReplyMetadata,
)

export const createScriptDataReplyDelegate =
	createPacketDelegate<ScriptDataReplyData>(scriptDataReplyMetadata)
