/**
 * SendPostcard Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { Bool, UUID, Variable1, Variable2, Vector3D } from "../types"

export interface SendPostcardData {
	agentData: {
		agentId?: string
		sessionId?: string
		assetId: string
		posGlobal: Vector3D
		to: string | Buffer
		from: string | Buffer
		name: string | Buffer
		subject: string | Buffer
		msg: string | Buffer
		allowPublish: boolean
		maturePublish: boolean
	}
}

export const sendPostcardMetadata = {
	id: 412,
	name: "SendPostcard",
	frequency: 2,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
				["assetId", UUID],
				["posGlobal", Vector3D],
				["to", Variable1],
				["from", Variable1],
				["name", Variable1],
				["subject", Variable1],
				["msg", Variable2],
				["allowPublish", Bool],
				["maturePublish", Bool],
			],
		},
	],
} satisfies PacketMetadata

export const sendPostcard =
	createPacketSender<SendPostcardData>(sendPostcardMetadata)

export const createSendPostcardDelegate =
	createPacketDelegate<SendPostcardData>(sendPostcardMetadata)
