/**
 * SetFollowCamProperties Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface SetFollowCamPropertiesData {
	objectData?: {
		objectId: string | Buffer
	}
	cameraProperty?: {
		type: number
		value: number
	}[]
}

export class SetFollowCamProperties extends Packet<SetFollowCamPropertiesData> {
	public static override id = 159
	public static override frequency = 0
	public static override trusted = true
	public static override compression = false

	public static override format = new Map([
		[
			"objectData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([["objectId", Types.UUID]]),
			},
		],
		[
			"cameraProperty",
			{
				parameters: new Map<string, Types.Type>([
					["type", Types.S32],
					["value", Types.F32],
				]),
			},
		],
	])
}
