/**
 * SetGroupAcceptNotices Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { Bool, UUID } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface SetGroupAcceptNoticesData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	data?: {
		groupId: string
		acceptNotices: boolean
	}
	newData?: {
		listInProfile: boolean
	}
}

export const setGroupAcceptNoticesMetadata = {
	id: 370,
	name: "SetGroupAcceptNotices",
	frequency: 2,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
			],
		},
		{
			name: "data",
			parameters: [
				["groupId", UUID],
				["acceptNotices", Bool],
			],
		},
		{
			name: "newData",
			parameters: [["listInProfile", Bool]],
		},
	],
} satisfies PacketMetadata

export const setGroupAcceptNotices =
	createPacketSender<SetGroupAcceptNoticesData>(setGroupAcceptNoticesMetadata)

export const createSetGroupAcceptNoticesDelegate =
	createPacketDelegate<SetGroupAcceptNoticesData>(setGroupAcceptNoticesMetadata)
