/**
 * SetSimPresenceInDatabase Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { S32, U32, UUID, Variable1 } from "../types"

export interface SetSimPresenceInDatabaseData {
	simData?: {
		regionId: string
		hostName: string | Buffer
		gridX: number
		gridY: number
		pid: number
		agentCount: number
		timeToLive: number
		status: string | Buffer
	}
}

export const setSimPresenceInDatabaseMetadata = {
	id: 23,
	name: "SetSimPresenceInDatabase",
	frequency: 2,
	trusted: true,
	blocks: [
		{
			name: "simData",
			parameters: [
				["regionId", UUID],
				["hostName", Variable1],
				["gridX", U32],
				["gridY", U32],
				["pid", S32],
				["agentCount", S32],
				["timeToLive", S32],
				["status", Variable1],
			],
		},
	],
} satisfies PacketMetadata

export const setSimPresenceInDatabase =
	createPacketSender<SetSimPresenceInDatabaseData>(
		setSimPresenceInDatabaseMetadata,
	)

export const createSetSimPresenceInDatabaseDelegate =
	createPacketDelegate<SetSimPresenceInDatabaseData>(
		setSimPresenceInDatabaseMetadata,
	)
