/**
 * SetSimStatusInDatabase Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface SetSimStatusInDatabaseData {
	data?: {
		regionId: string
		hostName: string | Buffer
		x: number
		y: number
		pid: number
		agentCount: number
		timeToLive: number
		status: string | Buffer
	}
}

export class SetSimStatusInDatabase extends Packet<SetSimStatusInDatabaseData> {
	public static override id = 22
	public static override frequency = 0
	public static override trusted = true
	public static override compression = false

	public static override format = new Map([
		[
			"data",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["regionId", Types.UUID],
					["hostName", Types.Variable1],
					["x", Types.S32],
					["y", Types.S32],
					["pid", Types.S32],
					["agentCount", Types.S32],
					["timeToLive", Types.S32],
					["status", Types.Variable1],
				]),
			},
		],
	])
}
