/**
 * SetGroupContribution Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { S32, UUID } from "../types"

export interface SetGroupContributionData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	data?: {
		groupId: string
		contribution: number
	}
}

export const setGroupContributionMetadata = {
	id: 369,
	name: "SetGroupContribution",
	frequency: 2,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
			],
		},
		{
			name: "data",
			parameters: [
				["groupId", UUID],
				["contribution", S32],
			],
		},
	],
} satisfies PacketMetadata

export const setGroupContribution =
	createPacketSender<SetGroupContributionData>(setGroupContributionMetadata)

export const createSetGroupContributionDelegate =
	createPacketDelegate<SetGroupContributionData>(setGroupContributionMetadata)
