/**
 * SetStartLocation Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { U32, U64, UUID, Vector3 } from "../types"

export interface SetStartLocationData {
	startLocationData?: {
		agentId: string
		regionId: string
		locationId: number
		regionHandle: number | bigint
		locationPos: Vector3
		locationLookAt: Vector3
	}
}

export const setStartLocationMetadata = {
	id: 325,
	name: "SetStartLocation",
	frequency: 2,
	trusted: true,
	compression: true,
	blocks: [
		{
			name: "startLocationData",
			parameters: [
				["agentId", UUID],
				["regionId", UUID],
				["locationId", U32],
				["regionHandle", U64],
				["locationPos", Vector3],
				["locationLookAt", Vector3],
			],
		},
	],
} satisfies PacketMetadata

export const setStartLocation = createPacketSender<SetStartLocationData>(
	setStartLocationMetadata,
)

export const createSetStartLocationDelegate =
	createPacketDelegate<SetStartLocationData>(setStartLocationMetadata)
