/**
 * SimStats Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { F32, S32, U32, U64 } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface SimStatsData {
	region?: {
		regionX: number
		regionY: number
		regionFlags: number
		objectCapacity: number
	}
	stat?: {
		statId: number
		statValue: number
	}[]
	pidStat?: {
		pid: number
	}
	regionInfo?: {
		regionFlagsExtended: number | bigint
	}[]
}

export const simStatsMetadata = {
	id: 140,
	name: "SimStats",
	frequency: 2,
	trusted: true,
	blocks: [
		{
			name: "region",
			parameters: [
				["regionX", U32],
				["regionY", U32],
				["regionFlags", U32],
				["objectCapacity", U32],
			],
		},
		{
			name: "stat",
			parameters: [
				["statId", U32],
				["statValue", F32],
			],
			multiple: true,
		},
		{
			name: "pidStat",
			parameters: [["pid", S32]],
		},
		{
			name: "regionInfo",
			parameters: [["regionFlagsExtended", U64]],
			multiple: true,
		},
	],
} satisfies PacketMetadata

export const simStats = createPacketSender<SimStatsData>(simStatsMetadata)

export const createSimStatsDelegate =
	createPacketDelegate<SimStatsData>(simStatsMetadata)
