/**
 * SimWideDeletes Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { U32, UUID } from "../types"

export interface SimWideDeletesData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	dataBlock?: {
		targetId: string
		flags: number
	}
}

export const simWideDeletesMetadata = {
	id: 129,
	name: "SimWideDeletes",
	frequency: 2,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
			],
		},
		{
			name: "dataBlock",
			parameters: [
				["targetId", UUID],
				["flags", U32],
			],
		},
	],
} satisfies PacketMetadata

export const simWideDeletes = createPacketSender<SimWideDeletesData>(
	simWideDeletesMetadata,
)

export const createSimWideDeletesDelegate =
	createPacketDelegate<SimWideDeletesData>(simWideDeletesMetadata)
