/**
 * SoundTrigger Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "~/network/types"
import { Packet } from "./packet"

export interface SoundTriggerData {
	soundData?: {
		soundId: string
		ownerId: string
		objectId: string
		parentId: string
		handle: number | bigint
		position: Types.Vector3
		gain: number
	}
}

export class SoundTrigger extends Packet<SoundTriggerData> {
	public static override id = 29
	public static override frequency = 2
	public static override trusted = false
	public static override compression = false

	public static override format = new Map([
		[
			"soundData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["soundId", Types.UUID],
					["ownerId", Types.UUID],
					["objectId", Types.UUID],
					["parentId", Types.UUID],
					["handle", Types.U64],
					["position", Types.Vector3],
					["gain", Types.F32],
				]),
			},
		],
	])
}
