/**
 * StartGroupProposal Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface StartGroupProposalData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	proposalData?: {
		groupId: string
		quorum: number
		majority: number
		duration: number
		proposalText: string | Buffer
	}
}

export class StartGroupProposal extends Packet<StartGroupProposalData> {
	public static override id = 363
	public static override frequency = 0
	public static override trusted = false
	public static override compression = true

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["agentId", Types.UUID],
					["sessionId", Types.UUID],
				]),
			},
		],
		[
			"proposalData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["groupId", Types.UUID],
					["quorum", Types.S32],
					["majority", Types.F32],
					["duration", Types.S32],
					["proposalText", Types.Variable1],
				]),
			},
		],
	])
}
