/**
 * StartPingCheck Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { U8, U32 } from "../types"

export interface StartPingCheckData {
	pingId?: {
		pingId: number
		oldestUnacked: number
	}
}

export const startPingCheckMetadata = {
	id: 1,
	name: "StartPingCheck",
	blocks: [
		{
			name: "pingId",
			parameters: [
				["pingId", U8],
				["oldestUnacked", U32],
			],
		},
	],
} satisfies PacketMetadata

export const startPingCheck = createPacketSender<StartPingCheckData>(
	startPingCheckMetadata,
)

export const createStartPingCheckDelegate =
	createPacketDelegate<StartPingCheckData>(startPingCheckMetadata)
