/**
 * StartPingCheck Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface StartPingCheckData {
	pingId?: {
		pingId: number
		oldestUnacked: number
	}
}

export class StartPingCheck extends Packet<StartPingCheckData> {
	public static override id = 1
	public static override frequency = 2
	public static override trusted = false
	public static override compression = false

	public static override format = new Map([
		[
			"pingId",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["pingId", Types.U8],
					["oldestUnacked", Types.U32],
				]),
			},
		],
	])
}
