/**
 * StartLure Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { U8, UUID, Variable1 } from "../types"

export interface StartLureData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	info?: {
		lureType: number
		message: string | Buffer
	}
	targetData?: {
		targetId: string
	}[]
}

export const startLureMetadata = {
	id: 70,
	name: "StartLure",
	frequency: 2,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
			],
		},
		{
			name: "info",
			parameters: [
				["lureType", U8],
				["message", Variable1],
			],
		},
		{
			name: "targetData",
			parameters: [["targetId", UUID]],
			multiple: true,
		},
	],
} satisfies PacketMetadata

export const startLure = createPacketSender<StartLureData>(startLureMetadata)

export const createStartLureDelegate =
	createPacketDelegate<StartLureData>(startLureMetadata)
