/**
 * StateSave Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface StateSaveData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	dataBlock?: {
		filename: string | Buffer
	}
}

export class StateSave extends Packet<StateSaveData> {
	public static override id = 127
	public static override frequency = 0
	public static override trusted = false
	public static override compression = false

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["agentId", Types.UUID],
					["sessionId", Types.UUID],
				]),
			},
		],
		[
			"dataBlock",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["filename", Types.Variable1],
				]),
			},
		],
	])
}
