/**
 * SystemMessage Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { Fixed32, UUID, Variable1 } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface SystemMessageData {
	methodData?: {
		method: string | Buffer
		invoice: string
		digest: string | Buffer
	}
	paramList?: {
		parameter: string | Buffer
	}[]
}

export const systemMessageMetadata = {
	id: 404,
	name: "SystemMessage",
	frequency: 2,
	trusted: true,
	compression: true,
	blocks: [
		{
			name: "methodData",
			parameters: [
				["method", Variable1],
				["invoice", UUID],
				["digest", Fixed32],
			],
		},
		{
			name: "paramList",
			parameters: [["parameter", Variable1]],
			multiple: true,
		},
	],
} satisfies PacketMetadata

export const systemMessage = createPacketSender<SystemMessageData>(
	systemMessageMetadata,
)

export const createSystemMessageDelegate =
	createPacketDelegate<SystemMessageData>(systemMessageMetadata)
