/**
 * SystemMessage Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "~/network/types"
import { Packet } from "./packet"

export interface SystemMessageData {
	methodData?: {
		method: string | Buffer
		invoice: string
		digest: string | Buffer
	}
	paramList?: {
		parameter: string | Buffer
	}[]
}

export class SystemMessage extends Packet<SystemMessageData> {
	public static override id = 404
	public static override frequency = 0
	public static override trusted = true
	public static override compression = true

	public static override format = new Map([
		[
			"methodData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["method", Types.Variable1],
					["invoice", Types.UUID],
					["digest", Types.Fixed32],
				]),
			},
		],
		[
			"paramList",
			{
				parameters: new Map<string, Types.Type>([
					["parameter", Types.Variable1],
				]),
			},
		],
	])
}
