/**
 * TallyVotes Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"

export type TallyVotesData = Record<string, never>

export const tallyVotesMetadata = {
	id: 365,
	name: "TallyVotes",
	frequency: 2,
	trusted: true,
} satisfies PacketMetadata

export const tallyVotes = createPacketSender<TallyVotesData>(tallyVotesMetadata)

export const createTallyVotesDelegate =
	createPacketDelegate<TallyVotesData>(tallyVotesMetadata)
