/**
 * TallyVotes Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { Packet } from "./packet"

export type TallyVotesData = Record<string, never>

export class TallyVotes extends Packet<TallyVotesData> {
	public static override id = 365
	public static override frequency = 0
	public static override trusted = true
	public static override compression = false
}
