/**
 * TeleportRequest Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { UUID, Vector3 } from "../types"

export interface TeleportRequestData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	info?: {
		regionId: string
		position: Vector3
		lookAt: Vector3
	}
}

export const teleportRequestMetadata = {
	id: 62,
	name: "TeleportRequest",
	frequency: 2,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
			],
		},
		{
			name: "info",
			parameters: [
				["regionId", UUID],
				["position", Vector3],
				["lookAt", Vector3],
			],
		},
	],
} satisfies PacketMetadata

export const teleportRequest = createPacketSender<TeleportRequestData>(
	teleportRequestMetadata,
)

export const createTeleportRequestDelegate =
	createPacketDelegate<TeleportRequestData>(teleportRequestMetadata)
