/**
 * TeleportRequest Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "~/network/types"
import { Packet } from "./packet"

export interface TeleportRequestData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	info?: {
		regionId: string
		position: Types.Vector3
		lookAt: Types.Vector3
	}
}

export class TeleportRequest extends Packet<TeleportRequestData> {
	public static override id = 62
	public static override frequency = 0
	public static override trusted = false
	public static override compression = false

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["agentId", Types.UUID],
					["sessionId", Types.UUID],
				]),
			},
		],
		[
			"info",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["regionId", Types.UUID],
					["position", Types.Vector3],
					["lookAt", Types.Vector3],
				]),
			},
		],
	])
}
