/**
 * TeleportFailed Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { UUID, Variable1 } from "../types"

export interface TeleportFailedData {
	info?: {
		agentId: string
		reason: string | Buffer
	}
	alertInfo?: {
		message: string | Buffer
		extraParams: string | Buffer
	}[]
}

export const teleportFailedMetadata = {
	id: 74,
	name: "TeleportFailed",
	frequency: 2,
	trusted: true,
	blocks: [
		{
			name: "info",
			parameters: [
				["agentId", UUID],
				["reason", Variable1],
			],
		},
		{
			name: "alertInfo",
			parameters: [
				["message", Variable1],
				["extraParams", Variable1],
			],
			multiple: true,
		},
	],
} satisfies PacketMetadata

export const teleportFailed = createPacketSender<TeleportFailedData>(
	teleportFailedMetadata,
)

export const createTeleportFailedDelegate =
	createPacketDelegate<TeleportFailedData>(teleportFailedMetadata)
