/**
 * TeleportLocationRequest Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { U64, UUID, Vector3 } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface TeleportLocationRequestData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	info?: {
		regionHandle: number | bigint
		position: Vector3
		lookAt: Vector3
	}
}

export const teleportLocationRequestMetadata = {
	id: 63,
	name: "TeleportLocationRequest",
	frequency: 2,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
			],
		},
		{
			name: "info",
			parameters: [
				["regionHandle", U64],
				["position", Vector3],
				["lookAt", Vector3],
			],
		},
	],
} satisfies PacketMetadata

export const teleportLocationRequest =
	createPacketSender<TeleportLocationRequestData>(
		teleportLocationRequestMetadata,
	)

export const createTeleportLocationRequestDelegate =
	createPacketDelegate<TeleportLocationRequestData>(
		teleportLocationRequestMetadata,
	)
