/**
 * TeleportStart Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { U32 } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface TeleportStartData {
	info?: {
		teleportFlags: number
	}
}

export const teleportStartMetadata = {
	id: 73,
	name: "TeleportStart",
	frequency: 2,
	trusted: true,
	blocks: [
		{
			name: "info",
			parameters: [["teleportFlags", U32]],
		},
	],
} satisfies PacketMetadata

export const teleportStart = createPacketSender<TeleportStartData>(
	teleportStartMetadata,
)

export const createTeleportStartDelegate =
	createPacketDelegate<TeleportStartData>(teleportStartMetadata)
