/**
 * TeleportLocal Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { U32, UUID, Vector3 } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface TeleportLocalData {
	info?: {
		agentId: string
		locationId: number
		position: Vector3
		lookAt: Vector3
		teleportFlags: number
	}
}

export const teleportLocalMetadata = {
	id: 64,
	name: "TeleportLocal",
	frequency: 2,
	trusted: true,
	blocks: [
		{
			name: "info",
			parameters: [
				["agentId", UUID],
				["locationId", U32],
				["position", Vector3],
				["lookAt", Vector3],
				["teleportFlags", U32],
			],
		},
	],
} satisfies PacketMetadata

export const teleportLocal = createPacketSender<TeleportLocalData>(
	teleportLocalMetadata,
)

export const createTeleportLocalDelegate =
	createPacketDelegate<TeleportLocalData>(teleportLocalMetadata)
