/**
 * TeleportProgress Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { U32, UUID, Variable1 } from "../types"

export interface TeleportProgressData {
	agentData?: {
		agentId?: string
	}
	info?: {
		teleportFlags: number
		message: string | Buffer
	}
}

export const teleportProgressMetadata = {
	id: 66,
	name: "TeleportProgress",
	frequency: 2,
	trusted: true,
	blocks: [
		{
			name: "agentData",
			parameters: [["agentId", UUID]],
		},
		{
			name: "info",
			parameters: [
				["teleportFlags", U32],
				["message", Variable1],
			],
		},
	],
} satisfies PacketMetadata

export const teleportProgress = createPacketSender<TeleportProgressData>(
	teleportProgressMetadata,
)

export const createTeleportProgressDelegate =
	createPacketDelegate<TeleportProgressData>(teleportProgressMetadata)
