/**
 * TeleportCancel Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { UUID } from "../types"

export interface TeleportCancelData {
	info?: {
		agentId: string
		sessionId: string
	}
}

export const teleportCancelMetadata = {
	id: 72,
	name: "TeleportCancel",
	frequency: 2,
	blocks: [
		{
			name: "info",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
			],
		},
	],
} satisfies PacketMetadata

export const teleportCancel = createPacketSender<TeleportCancelData>(
	teleportCancelMetadata,
)

export const createTeleportCancelDelegate =
	createPacketDelegate<TeleportCancelData>(teleportCancelMetadata)
