/**
 * TeleportLocal Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface TeleportLocalData {
	info?: {
		agentId: string
		locationId: number
		position: Types.Vector3
		lookAt: Types.Vector3
		teleportFlags: number
	}
}

export class TeleportLocal extends Packet<TeleportLocalData> {
	public static override id = 64
	public static override frequency = 0
	public static override trusted = true
	public static override compression = false

	public static override format = new Map([
		[
			"info",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["agentId", Types.UUID],
					["locationId", Types.U32],
					["position", Types.Vector3],
					["lookAt", Types.Vector3],
					["teleportFlags", Types.U32],
				]),
			},
		],
	])
}
