/**
 * TransferInfo Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "~/network/types"
import { Packet } from "./packet"

export interface TransferInfoData {
	transferInfo?: {
		transferId: string
		channelType: number
		targetType: number
		status: number
		size: number
		params: string | Buffer
	}
}

export class TransferInfo extends Packet<TransferInfoData> {
	public static override id = 154
	public static override frequency = 0
	public static override trusted = false
	public static override compression = true

	public static override format = new Map([
		[
			"transferInfo",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["transferId", Types.UUID],
					["channelType", Types.S32],
					["targetType", Types.S32],
					["status", Types.S32],
					["size", Types.S32],
					["params", Types.Variable2],
				]),
			},
		],
	])
}
