/**
 * TransferInventoryAck Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "~/network/types"
import { Packet } from "./packet"

export interface TransferInventoryAckData {
	infoBlock?: {
		transactionId: string
		inventoryId: string
	}
}

export class TransferInventoryAck extends Packet<TransferInventoryAckData> {
	public static override id = 296
	public static override frequency = 0
	public static override trusted = true
	public static override compression = true

	public static override format = new Map([
		[
			"infoBlock",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["transactionId", Types.UUID],
					["inventoryId", Types.UUID],
				]),
			},
		],
	])
}
