/**
 * TransferPacket Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { S32, UUID, Variable2 } from "../types"

export interface TransferPacketData {
	transferData?: {
		transferId: string
		channelType: number
		packet: number
		status: number
		data: string | Buffer
	}
}

export const transferPacketMetadata = {
	id: 17,
	name: "TransferPacket",
	blocks: [
		{
			name: "transferData",
			parameters: [
				["transferId", UUID],
				["channelType", S32],
				["packet", S32],
				["status", S32],
				["data", Variable2],
			],
		},
	],
} satisfies PacketMetadata

export const transferPacket = createPacketSender<TransferPacketData>(
	transferPacketMetadata,
)

export const createTransferPacketDelegate =
	createPacketDelegate<TransferPacketData>(transferPacketMetadata)
