/**
 * TransferRequest Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { F32, S32, UUID, Variable2 } from "../types"

export interface TransferRequestData {
	transferInfo?: {
		transferId: string
		channelType: number
		sourceType: number
		priority: number
		params: string | Buffer
	}
}

export const transferRequestMetadata = {
	id: 153,
	name: "TransferRequest",
	frequency: 2,
	compression: true,
	blocks: [
		{
			name: "transferInfo",
			parameters: [
				["transferId", UUID],
				["channelType", S32],
				["sourceType", S32],
				["priority", F32],
				["params", Variable2],
			],
		},
	],
} satisfies PacketMetadata

export const transferRequest = createPacketSender<TransferRequestData>(
	transferRequestMetadata,
)

export const createTransferRequestDelegate =
	createPacketDelegate<TransferRequestData>(transferRequestMetadata)
