/**
 * Undo Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { UUID } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface UndoData {
	agentData: {
		agentId?: string
		sessionId?: string
		groupId: string
	}
	objectData?: {
		objectId: string
	}[]
}

export const undoMetadata = {
	id: 75,
	name: "Undo",
	frequency: 2,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
				["groupId", UUID],
			],
		},
		{
			name: "objectData",
			parameters: [["objectId", UUID]],
			multiple: true,
		},
	],
} satisfies PacketMetadata

export const undo = createPacketSender<UndoData>(undoMetadata)

export const createUndoDelegate = createPacketDelegate<UndoData>(undoMetadata)
