/**
 * UpdateAttachment Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface UpdateAttachmentData {
	agentData?: {
		agentId?: string | Buffer
		sessionId?: string | Buffer
	}
	attachmentBlock?: {
		attachmentPoint: number
	}
	operationData?: {
		addItem: boolean
		useExistingAsset: boolean
	}
}

export class UpdateAttachment extends Packet<UpdateAttachmentData> {
	public static override id = 331
	public static override frequency = 0
	public static override trusted = true
	public static override compression = true

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["agentId", Types.UUID],
					["sessionId", Types.UUID],
				]),
			},
		],
		[
			"attachmentBlock",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["attachmentPoint", Types.U8],
				]),
			},
		],
		[
			"operationData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["addItem", Types.Bool],
					["useExistingAsset", Types.Bool],
				]),
			},
		],
	])
}
