/**
 * UpdateMuteListEntry Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { S32, U32, UUID, Variable1 } from "../types"

export interface UpdateMuteListEntryData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	muteData?: {
		muteId: string
		muteName: string | Buffer
		muteType: number
		muteFlags: number
	}
}

export const updateMuteListEntryMetadata = {
	id: 263,
	name: "UpdateMuteListEntry",
	frequency: 2,
	blocks: [
		{
			name: "agentData",
			parameters: [
				["agentId", UUID],
				["sessionId", UUID],
			],
		},
		{
			name: "muteData",
			parameters: [
				["muteId", UUID],
				["muteName", Variable1],
				["muteType", S32],
				["muteFlags", U32],
			],
		},
	],
} satisfies PacketMetadata

export const updateMuteListEntry = createPacketSender<UpdateMuteListEntryData>(
	updateMuteListEntryMetadata,
)

export const createUpdateMuteListEntryDelegate =
	createPacketDelegate<UpdateMuteListEntryData>(updateMuteListEntryMetadata)
