/**
 * UseCircuitCode Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface UseCircuitCodeData {
	circuitCode?: {
		code: number
		sessionId: string | Buffer
		id: string | Buffer
	}
}

export class UseCircuitCode extends Packet<UseCircuitCodeData> {
	public static override id = 3
	public static override frequency = 0
	public static override trusted = false
	public static override compression = false

	public static override format = new Map([
		[
			"circuitCode",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["code", Types.U32],
					["sessionId", Types.UUID],
					["id", Types.UUID],
				]),
			},
		],
	])
}
