/**
 * UseCircuitCode Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { U32, UUID } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface UseCircuitCodeData {
	circuitCode?: {
		code: number
		sessionId: string
		id: string
	}
}

export const useCircuitCodeMetadata = {
	id: 3,
	name: "UseCircuitCode",
	frequency: 2,
	blocks: [
		{
			name: "circuitCode",
			parameters: [
				["code", U32],
				["sessionId", UUID],
				["id", UUID],
			],
		},
	],
} satisfies PacketMetadata

export const useCircuitCode = createPacketSender<UseCircuitCodeData>(
	useCircuitCodeMetadata,
)

export const createUseCircuitCodeDelegate =
	createPacketDelegate<UseCircuitCodeData>(useCircuitCodeMetadata)
