/**
 * UserReport Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "~/network/types"
import { Packet } from "./packet"

export interface UserReportData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	reportData?: {
		reportType: number
		category: number
		position: Types.Vector3
		checkFlags: number
		screenshotId: string
		objectId: string
		abuserId: string
		abuseRegionName: string | Buffer
		abuseRegionId: string
		summary: string | Buffer
		details: string | Buffer
		versionString: string | Buffer
	}
}

export class UserReport extends Packet<UserReportData> {
	public static override id = 133
	public static override frequency = 0
	public static override trusted = false
	public static override compression = true

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["agentId", Types.UUID],
					["sessionId", Types.UUID],
				]),
			},
		],
		[
			"reportData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["reportType", Types.U8],
					["category", Types.U8],
					["position", Types.Vector3],
					["checkFlags", Types.U8],
					["screenshotId", Types.UUID],
					["objectId", Types.UUID],
					["abuserId", Types.UUID],
					["abuseRegionName", Types.Variable1],
					["abuseRegionId", Types.UUID],
					["summary", Types.Variable1],
					["details", Types.Variable2],
					["versionString", Types.Variable1],
				]),
			},
		],
	])
}
