/**
 * UserInfoReply Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { Bool, UUID, Variable1, Variable2 } from "../types"

export interface UserInfoReplyData {
	agentData?: {
		agentId?: string
	}
	userData?: {
		imViaEMail: boolean
		directoryVisibility: string | Buffer
		eMail: string | Buffer
	}
}

export const userInfoReplyMetadata = {
	id: 400,
	name: "UserInfoReply",
	frequency: 2,
	blocks: [
		{
			name: "agentData",
			parameters: [["agentId", UUID]],
		},
		{
			name: "userData",
			parameters: [
				["imViaEMail", Bool],
				["directoryVisibility", Variable1],
				["eMail", Variable2],
			],
		},
	],
} satisfies PacketMetadata

export const userInfoReply = createPacketSender<UserInfoReplyData>(
	userInfoReplyMetadata,
)

export const createUserInfoReplyDelegate =
	createPacketDelegate<UserInfoReplyData>(userInfoReplyMetadata)
