/**
 * UUIDGroupNameReply Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { UUID, Variable1 } from "../types"

export interface UUIDGroupNameReplyData {
	uuidNameBlock?: {
		id: string
		groupName: string | Buffer
	}[]
}

export const uuidGroupNameReplyMetadata = {
	id: 238,
	name: "UUIDGroupNameReply",
	frequency: 2,
	trusted: true,
	blocks: [
		{
			name: "uuidNameBlock",
			parameters: [
				["id", UUID],
				["groupName", Variable1],
			],
			multiple: true,
		},
	],
} satisfies PacketMetadata

export const uuidGroupNameReply = createPacketSender<UUIDGroupNameReplyData>(
	uuidGroupNameReplyMetadata,
)

export const createUUIDGroupNameReplyDelegate =
	createPacketDelegate<UUIDGroupNameReplyData>(uuidGroupNameReplyMetadata)
