/**
 * UUIDGroupNameRequest Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "../packet"
import { UUID } from "../types"

export interface UUIDGroupNameRequestData {
	uuidNameBlock?: {
		id: string
	}[]
}

export const uuidGroupNameRequestMetadata = {
	id: 237,
	name: "UUIDGroupNameRequest",
	frequency: 2,
	blocks: [
		{
			name: "uuidNameBlock",
			parameters: [["id", UUID]],
			multiple: true,
		},
	],
} satisfies PacketMetadata

export const uuidGroupNameRequest =
	createPacketSender<UUIDGroupNameRequestData>(uuidGroupNameRequestMetadata)

export const createUUIDGroupNameRequestDelegate =
	createPacketDelegate<UUIDGroupNameRequestData>(uuidGroupNameRequestMetadata)
