/**
 * UUIDNameRequest Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import { UUID } from "../types"
import {
	createPacketDelegate,
	createPacketSender,
	type PacketMetadata,
} from "./packet"

export interface UUIDNameRequestData {
	uuidNameBlock?: {
		id: string
	}[]
}

export const uuidNameRequestMetadata = {
	id: 235,
	name: "UUIDNameRequest",
	frequency: 2,
	blocks: [
		{
			name: "uuidNameBlock",
			parameters: [["id", UUID]],
			multiple: true,
		},
	],
} satisfies PacketMetadata

export const uuidNameRequest = createPacketSender<UUIDNameRequestData>(
	uuidNameRequestMetadata,
)

export const createUUIDNameRequestDelegate =
	createPacketDelegate<UUIDNameRequestData>(uuidNameRequestMetadata)
