/**
 * ViewerStartAuction Packet
 *
 * This file is used to help our packet serialization and deserialization
 * process, and to create new packets on the fly.
 *
 * ⚠️ Do not edit this file manually, it is generated by the `codegen` script!
 *
 * @see {@link http://wiki.secondlife.com/wiki/Message_Layout}
 */

import * as Types from "../types"
import { Packet } from "./packet"

export interface ViewerStartAuctionData {
	agentData?: {
		agentId?: string
		sessionId?: string
	}
	parcelData?: {
		localId: number
		snapshotId: string
	}
}

export class ViewerStartAuction extends Packet<ViewerStartAuctionData> {
	public static override id = 228
	public static override frequency = 0
	public static override trusted = false
	public static override compression = false

	public static override format = new Map([
		[
			"agentData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["agentId", Types.UUID],
					["sessionId", Types.UUID],
				]),
			},
		],
		[
			"parcelData",
			{
				quantity: 1,
				parameters: new Map<string, Types.Type>([
					["localId", Types.S32],
					["snapshotId", Types.UUID],
				]),
			},
		],
	])
}
